In [1]:
import pandas as pd

In [2]:
import sys
print(sys.executable)

c:\Users\Admin\Documents\amazon\.venv\Scripts\python.exe

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import numpy as np

In [5]:
year_2015 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2015.csv")
year_2015.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

In [6]:
year_2015.count()

transaction_id            33165
order_date                33165
customer_id               33165
product_id                33165
product_name              33165
category                  33165
subcategory               33165
brand                     33165
original_price_inr        33165
discount_percent          33165
discounted_price_inr      33165
quantity                  33165
subtotal_inr              33165
delivery_charges          30511
final_amount_inr          33165
customer_city             33165
customer_state            33165
customer_tier             33165
customer_spending_tier    33165
customer_age_group        29189
payment_method            33165
delivery_days             33165
delivery_type             33165
is_prime_member           33165
is_festival_sale          33165
festival_name             10584
customer_rating           23196
return_status             33165
order_month               33165
order_year                33165
order_quarter             33165
product_weight_kg         33165
is_prime_eligible         33165
product_rating            33165
dtype: int64

In [7]:
year_2015.isna().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           2654
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         3976
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             22581
customer_rating            9969
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [8]:


year_2015.info()

<class 'pandas.DataFrame'>
RangeIndex: 33165 entries, 0 to 33164
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaction_id          33165 non-null  str
 1   order_date              33165 non-null  str
 2   customer_id             33165 non-null  str
 3   product_id              33165 non-null  str
 4   product_name            33165 non-null  str
 5   category                33165 non-null  str
 6   subcategory             33165 non-null  str
 7   brand                   33165 non-null  str
 8   original_price_inr      33165 non-null  str
 9   discount_percent        33165 non-null  float64
 10  discounted_price_inr    33165 non-null  float64
 11  quantity                33165 non-null  int64
 12  subtotal_inr            33165 non-null  float64
 13  delivery_charges        30511 non-null  float64
 14  final_amount_inr        33165 non-null  float64
 15  customer_city           33165 non-null  str
 16  customer_state          33165 non-null  str
 17  customer_tier           33165 non-null  str
 18  customer_spending_tier  33165 non-null  str
 19  customer_age_group      29189 non-null  str
 20  payment_method          33165 non-null  str
 21  delivery_days           33165 non-null  str
 22  delivery_type           33165 non-null  str
 23  is_prime_member         33165 non-null  str
 24  is_festival_sale        33165 non-null  str
 25  festival_name           10584 non-null  str
 26  customer_rating         23196 non-null  str
 27  return_status           33165 non-null  str
 28  order_month             33165 non-null  int64
 29  order_year              33165 non-null  int64
 30  order_quarter           33165 non-null  int64
 31  product_weight_kg       33165 non-null  float64
 32  is_prime_eligible       33165 non-null  str
 33  product_rating          33165 non-null  float64
dtypes: float64(7), int64(4), str(23)
memory usage: 8.6 MB

In [9]:
year_2015.replace("", np.nan, inplace=True)

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33160,TXN_2015_00001578_DUP,2015-01-24,CUST_2015_00002994,PROD_000063,OnePlus OnePlus X 32GB Blue,Electronics,Smartphones,OnePlus,75380.48,45.58,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.18,True,3.8
33161,TXN_2015_00004573_DUP,2015-03-01,CUST_2015_00005528,PROD_001546,Dell MacBook 4GB RAM Silver,Electronics,Laptops,Dell,29350.42,22.28,...,True,Holi Festival,4.0,Delivered,3,2015,1,1.21,True,3.4
33162,TXN_2015_00003696_DUP,2015-02-27,CUST_2015_00011570,PROD_001710,Lenovo Tab M10 8GB RAM Black,Electronics,Tablets,Lenovo,56337.89,23.68,...,False,NaN,NaN,Delivered,2,2015,1,0.49,True,4.1
33163,TXN_2015_00032368_DUP,2015-12-04,CUST_2015_00005774,PROD_000083,Xiaomi Redmi Note 4G 16GB Blue,Electronics,Smartphones,Xiaomi,33199.84,0.00,...,False,NaN,NaN,Delivered,12,2015,4,0.15,False,4.1
33164,TXN_2015_00014927_DUP,2015-07-27,CUST_2015_00000326,PROD_000036,Samsung Galaxy S6 Edge 16GB Gold,Electronics,Smartphones,Samsung,88872.68,0.00,...,False,NaN,NaN,Delivered,7,2015,3,0.16,False,3.9

In [10]:
year_2015.isna().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           2654
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         3976
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             22581
customer_rating            9969
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [11]:
year_2015[year_2015.isna().any(axis=1)]

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1
5,TXN_2015_00000006,2015-01-04,CUST_2015_00006757,PROD_001665,Alienware MacBook 4GB RAM Black,Electronics,Laptops,Alienware,131194.65,0.00,...,False,NaN,4.5,Delivered,1,2015,1,1.39,No,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33159,TXN_2015_00023127_DUP,2015-10-24,CUST_2015_00007677,PROD_001839,Sennheiser TWS,Electronics,Audio,Sennheiser,10481.43,40.98,...,True,Diwali Sale,NaN,Delivered,10,2015,4,0.75,1,3.7
33161,TXN_2015_00004573_DUP,2015-03-01,CUST_2015_00005528,PROD_001546,Dell MacBook 4GB RAM Silver,Electronics,Laptops,Dell,29350.42,22.28,...,True,Holi Festival,4.0,Delivered,3,2015,1,1.21,True,3.4
33162,TXN_2015_00003696_DUP,2015-02-27,CUST_2015_00011570,PROD_001710,Lenovo Tab M10 8GB RAM Black,Electronics,Tablets,Lenovo,56337.89,23.68,...,False,NaN,NaN,Delivered,2,2015,1,0.49,True,4.1
33163,TXN_2015_00032368_DUP,2015-12-04,CUST_2015_00005774,PROD_000083,Xiaomi Redmi Note 4G 16GB Blue,Electronics,Smartphones,Xiaomi,33199.84,0.00,...,False,NaN,NaN,Delivered,12,2015,4,0.15,False,4.1
33164,TXN_2015_00014927_DUP,2015-07-27,CUST_2015_00000326,PROD_000036,Samsung Galaxy S6 Edge 16GB Gold,Electronics,Smartphones,Samsung,88872.68,0.00,...,False,NaN,NaN,Delivered,7,2015,3,0.16,False,3.9

In [12]:
year_2015['order_date'].unique()

<StringArray>
['2015-01-25', '2015-01-05', '2015-01-24', '2015-01-28', '2015-01-31',
 '2015-01-04', '2015-01-27', '2015-01-08', '2015-01-18', '2015-01-03',
 ...
 '18-12-2015', '13-12-2015', '28/12/2015', '09/12/2015', '10-12-2015',
 '07-12-2015', '15-12-2015', '12/20/2015', '12/28/2015', '12/15/2015']
Length: 1272, dtype: str

In [13]:
year_2015['order_date'] = pd.to_datetime(
    year_2015['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2015['order_date'].dropna().median()

year_2015['order_date'] = (
    year_2015['order_date']
    .fillna(median_date)
)

# Standardize format
year_2015['order_date'] = (
    year_2015['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [14]:
year_2015['delivery_days'].dtype

In [15]:
year_2015.isna().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           2654
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         3976
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             22581
customer_rating            9969
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [16]:
year_2015['category'].unique()

<StringArray>
[              'Electronics',               'ELECTRONICS',
 'Electronics & Accessories',                'Electronic',
              'Electronicss']
Length: 5, dtype: str

In [17]:
cols = ['is_prime_eligible', 'is_prime_member','is_festival_sale']

for col in cols:
    print(col)
    print(year_2015[col].unique())

is_prime_eligible
<StringArray>
['True', 'No', 'False', 'TRUE', '1', 'Yes', '0', 'FALSE']
Length: 8, dtype: str
is_prime_member
<StringArray>
['No', 'False', 'FALSE', '0']
Length: 4, dtype: str
is_festival_sale
<StringArray>
['True', 'False', 'FALSE', 'No', '0', '1', 'Yes', 'TRUE']
Length: 8, dtype: str

In [18]:
# The boolean columns have multiple representations of True and False. 
import numpy as np

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2015[col] = year_2015[col].map(bool_map)

In [19]:
cols = ['is_prime_eligible', 'is_prime_member','is_festival_sale']

for col in cols:
    print(col)
    print(year_2015[col].unique())

is_prime_eligible
[ True False]
is_prime_member
[False]
is_festival_sale
[ True False]

In [20]:
# The category column has multiple representations of the same category. We can standardize them using a mapping.
category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2015['category'] = (
    year_2015['category']
    .replace(category_map)
)

In [21]:
import pandas as pd
import numpy as np

# Replace text values with numeric equivalents
year_2015['delivery_days'] = year_2015['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2015['delivery_days'] = pd.to_numeric(
    year_2015['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2015.loc[
    (year_2015['delivery_days'] >= 0) &
    (year_2015['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2015.loc[
    (year_2015['delivery_days'] < 0) |
    (year_2015['delivery_days'] > 30) |
    (year_2015['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2015['delivery_days'] = year_2015['delivery_days'].astype(int)

In [22]:
suspected_duplicates = year_2015[
    year_2015.duplicated(
        subset=[
            'customer_id',
            'product_id',
            'order_date',
            'final_amount_inr'
        ],
        keep=False
    )
]

suspected_duplicates

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
279,TXN_2015_00000280,2015-01-29,CUST_2015_00010848,PROD_000027,Samsung Galaxy S6 16GB Blue,Electronics,Smartphones,Samsung,"Rs 130,430",21.03,...,False,NaN,4.0,Delivered,1,2015,1,0.18,True,3.4
814,TXN_2015_00000815,2015-01-31,CUST_2015_00001928,PROD_000059,OnePlus OnePlus X 32GB Black,Electronics,Smartphones,OnePlus,57182.39,0.00,...,False,NaN,5.0,Delivered,1,2015,1,0.20,True,3.8
941,TXN_2015_00000942,2015-03-01,CUST_2015_00007653,PROD_000075,Xiaomi Redmi 2 64GB White,Electronics,Smartphones,Xiaomi,35581.67,0.00,...,False,NaN,NaN,Delivered,1,2015,1,0.22,False,3.6
996,TXN_2015_00000997,2015-01-28,CUST_2015_00003254,PROD_000032,Samsung Galaxy S6 Edge 16GB White,Electronics,Smartphones,Samsung,97905.92,0.00,...,False,NaN,4.0,Delivered,1,2015,1,0.20,True,4.3
1390,TXN_2015_00001391,2015-01-15,CUST_2015_00005080,PROD_001640,MSI Aspire 4GB RAM Black,Electronics,Laptops,MSI,69584.33,12.76,...,False,NaN,4.5,Returned,1,2015,1,2.66,True,3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33160,TXN_2015_00001578_DUP,2015-01-24,CUST_2015_00002994,PROD_000063,OnePlus OnePlus X 32GB Blue,Electronics,Smartphones,OnePlus,75380.48,45.58,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.18,True,3.8
33161,TXN_2015_00004573_DUP,2015-01-03,CUST_2015_00005528,PROD_001546,Dell MacBook 4GB RAM Silver,Electronics,Laptops,Dell,29350.42,22.28,...,True,Holi Festival,4.0,Delivered,3,2015,1,1.21,True,3.4
33162,TXN_2015_00003696_DUP,2015-02-27,CUST_2015_00011570,PROD_001710,Lenovo Tab M10 8GB RAM Black,Electronics,Tablets,Lenovo,56337.89,23.68,...,False,NaN,NaN,Delivered,2,2015,1,0.49,True,4.1
33163,TXN_2015_00032368_DUP,2015-04-12,CUST_2015_00005774,PROD_000083,Xiaomi Redmi Note 4G 16GB Blue,Electronics,Smartphones,Xiaomi,33199.84,0.00,...,False,NaN,NaN,Delivered,12,2015,4,0.15,False,4.1
33164,TXN_2015_00014927_DUP,2015-07-27,CUST_2015_00000326,PROD_000036,Samsung Galaxy S6 Edge 16GB Gold,Electronics,Smartphones,Samsung,88872.68,0.00,...,False,NaN,NaN,Delivered,7,2015,3,0.16,False,3.9

In [23]:
duplicate_summary = (
    suspected_duplicates
    .groupby([
        'customer_id',
        'product_id',
        'order_date',
        'final_amount_inr'
    ])
    .size()
    .reset_index(name='duplicate_count')
)

duplicate_summary.sort_values(
    by='duplicate_count',
    ascending=False
)

,customer_id,product_id,order_date,final_amount_inr,duplicate_count
0,CUST_2015_00000037,PROD_000053,2015-01-23,82840.60,2
1,CUST_2015_00000173,PROD_001820,2015-05-23,16779.59,2
2,CUST_2015_00000265,PROD_000071,2015-08-25,132609.36,2
3,CUST_2015_00000326,PROD_000036,2015-07-27,88872.68,2
4,CUST_2015_00000433,PROD_000071,2015-08-09,40751.36,2
...,...,...,...,...,...
160,CUST_2015_00011692,PROD_000054,2015-09-04,49480.94,2
161,CUST_2015_00011774,PROD_002002,2015-09-23,101061.24,2
162,CUST_2015_00011955,PROD_000075,2015-07-20,35581.67,2
163,CUST_2015_00011995,PROD_000061,2015-11-10,82953.19,2
164,CUST_2015_00011999,PROD_000052,2015-09-19,60986.10,2

In [24]:
year_2015['duplicate_type'] = 'unique'

In [25]:
year_2015['duplicate_flag'] = year_2015.duplicated(
    subset=[
        'customer_id',
        'product_id',
        'order_date',
        'final_amount_inr'
    ],
    keep=False
)

In [26]:
exact_duplicates = year_2015[
    year_2015.duplicated(
        subset=[
            'customer_id',
            'product_id',
            'order_date',
            'quantity',
            'final_amount_inr',
            'payment_method',
            'delivery_days'
        ],
        keep='first'
    )
]

In [27]:
year_2015_cleaned = year_2015.drop_duplicates(
    subset=[
        'customer_id',
        'product_id',
        'order_date',
        'quantity',
        'final_amount_inr',
        'payment_method'
    ],
    keep='first'
)

In [28]:
year_2015['original_price_inr'].describe()

count        33165
unique         811
top       45363.47
freq           409
Name: original_price_inr, dtype: object

In [29]:
year_2015['original_price_inr'] = pd.to_numeric(
    year_2015['original_price_inr'],
    errors='coerce'
)

In [30]:
Q1 = year_2015['original_price_inr'].quantile(0.25)
Q3 = year_2015['original_price_inr'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [31]:
year_2015['original_price_inr'].unique()

array([ 1.2361429e+05,  5.4731860e+04,  9.7644250e+04,            nan,
        1.3119465e+05,  8.6987640e+04,  3.2169010e+04,  4.0264160e+04,
        8.8664850e+04,  7.3967020e+04,  7.2564100e+04,  2.0987555e+05,
        4.5363470e+04,  2.3075710e+04,  1.1409663e+05,  6.9584330e+04,
        3.8884190e+04,  4.6234090e+04,  1.5065010e+04,  1.6416684e+05,
        6.4917570e+04,  2.9534700e+04,  8.6477530e+04,  1.3721420e+04,
        1.1814116e+05,  8.6591570e+04,  2.3264310e+04,  9.4029640e+04,
        1.7206230e+04,  3.7013540e+04,  1.3043024e+05,  1.3072361e+05,
        4.1408670e+04,  7.5380480e+04,  2.3161100e+04,  4.6680900e+04,
        4.3572750e+04,  1.9375090e+04,  3.8969900e+03,  2.0006120e+04,
        3.0990650e+04,  5.6337890e+04,  2.2683690e+04,  1.0264914e+05,
        1.0738737e+05,  6.7444910e+04,  2.4762020e+04,  1.7790720e+04,
        2.4448870e+04,  1.0274122e+05,  5.1356920e+04,  3.3199840e+04,
        9.7531100e+03,  8.8872680e+04,  7.2369630e+04,  1.2645400e+05,
        7.8047800e+04,  6.0643250e+04,  1.4558980e+05,  9.6543620e+04,
        4.0438410e+04,  1.2984580e+04,  3.9490870e+04,  4.0307830e+04,
        6.2405020e+04,  1.1071950e+04,  8.2953190e+04,  2.0323890e+04,
        4.6458940e+04,  9.5494860e+04,  3.5581670e+04,  1.9046910e+05,
        1.9871970e+04,  2.1172116e+05,  2.5093870e+04,  2.1211500e+04,
        5.2280350e+04,  2.9350420e+04,  1.6954440e+05,  1.9864160e+04,
        1.7320342e+05,  1.3495030e+04,  7.6246510e+04,  5.6461600e+03,
        2.4160320e+04,  4.3767400e+04,  1.7349967e+05,  2.8668340e+04,
        2.3087980e+04,  2.6317100e+04,  7.4885610e+04,  9.7905920e+04,
        4.5182310e+04,  4.2790640e+04,  1.1480624e+05,  2.0175120e+04,
        1.3142121e+05,  4.7978890e+04,  2.2779490e+04,  1.3617695e+05,
        2.3391490e+04,  1.7869250e+04, -3.8884190e+04,  5.7182390e+04,
        3.1102540e+04,  7.7250030e+04,  1.8500958e+05,  3.9010090e+04,
        1.7979549e+05,  1.3267866e+05,  1.6795246e+05,  1.0481430e+04,
        1.1531600e+04,  1.1728933e+05,  9.4298200e+03,  1.0966446e+05,
        1.6482819e+05,  1.8053075e+05,  2.1456840e+04,  1.5595890e+05,
        1.7718710e+04,  1.7116370e+04,  1.8318573e+05,  1.1874051e+05,
        1.5074620e+05,  1.3758970e+05,  4.4830400e+04,  2.0321710e+04,
        2.9675170e+04,  2.1947260e+04,  2.0258290e+04,  1.8723201e+05,
        1.4094679e+05,  1.3440840e+04,  4.4830400e+05,  3.6350600e+04,
        3.9010090e+06,  4.4203120e+04,  1.5974247e+05, -1.3142121e+05,
        1.5228530e+04,  1.6406110e+04,  1.3930776e+05,  1.6927003e+05,
        1.7717090e+04,  1.5842489e+05,  1.4362600e+04,  8.9785000e+03,
        1.3344050e+04,  1.3965560e+04,  1.2171100e+04,  1.3790620e+04,
        2.0937460e+04,  1.3975159e+05,  1.8972448e+05,  1.1648020e+04,
        1.6286691e+05,  7.7205100e+03,  3.7950100e+03, -1.6795246e+05,
        1.2757300e+04,  1.8470489e+05,  1.4834657e+05,  1.3921720e+04,
        1.5201502e+05,  2.6317100e+06,  1.5126000e+05,  2.3748400e+03,
       -2.3391490e+04,  4.3767400e+06,  1.9864160e+05,  3.8884190e+06,
        7.2369630e+05,  1.1187990e+04,  1.1459640e+04,  6.7444910e+06,
        8.6477530e+05, -2.1456840e+04, -1.0264914e+05,  3.9490870e+05,
        1.7174290e+04,  5.6337890e+05,  4.4203120e+06,  1.1728933e+07,
        8.8872680e+05,  2.3161100e+05,  1.7869250e+06, -5.2280350e+04,
        2.0175120e+05,  2.9534700e+06,  1.9375090e+06,  3.5581670e+05,
        2.3748400e+04,  5.4731860e+06,  7.2564100e+06,  9.7644250e+06,
        1.1480624e+07,  1.2645400e+07,  3.6350600e+06, -3.9490870e+04,
        9.4029640e+05, -3.7013540e+04,  8.2953190e+06, -1.3495030e+04,
       -2.6317100e+04,  2.3075710e+05, -9.7905920e+04,  6.9584330e+05,
       -4.5182310e+04,  6.0643250e+05, -8.8872680e+04, -1.1187990e+04,
       -6.9584330e+04, -1.7349967e+05,  2.1211500e+05, -5.7182390e+04,
        3.2169010e+06, -2.1947260e+04,  7.2564100e+05, -2.3264310e+04,
       -1.1480624e+05,  4.0307830e+05,  4.0264160e+06, -7.7250030e+04,
       -8.6987640e+04,  1.2645400e+06,  3.7013540e+06,  2.0321710e+06,
       -3.1102540e+04,  4.2790640e+06,  1.2361429e+07,  2.5093870e+06,
       -7.4885610e+04, -9.7644250e+04,  4.6458940e+06,  2.0006120e+06,
        2.4160320e+05,  2.3391490e+05, -2.8668340e+04, -1.0274122e+05,
        2.9675170e+06,  8.6477530e+06,  6.9584330e+06,  1.6927003e+06,
       -1.3930776e+05,  1.3495030e+05,  2.2683690e+05,  2.3264310e+06,
        2.0175120e+06, -1.7790720e+04,  6.0643250e+06, -1.3043024e+05,
        7.4885610e+06,  1.0264914e+07,  1.3119465e+07,  2.1947260e+06,
        8.8664850e+06, -8.6591570e+04, -3.9010090e+04,  8.8664850e+05,
       -5.1356920e+04,  1.3072361e+06, -4.6680900e+04,  7.8047800e+05,
        4.6680900e+06,  1.5201502e+06, -1.8500958e+05,  7.5380480e+06,
        4.0438410e+05, -2.5093870e+04, -1.2645400e+05, -1.9864160e+04,
        1.0966446e+06,  4.5363470e+06,  1.1531600e+06, -5.6337890e+04,
       -3.3199840e+04,  1.2171100e+06, -2.0321710e+04,  1.2984580e+06,
       -9.4298200e+03,  1.1814116e+07,  2.8668340e+05, -3.2169010e+04,
        9.6543620e+05, -4.7978890e+04, -2.0175120e+04,  4.3767400e+05,
        2.1172116e+07, -6.2405020e+04, -2.9675170e+04, -4.6234090e+04,
        2.9675170e+05,  5.1356920e+06,  2.1947260e+05, -1.9375090e+04,
       -1.3921720e+04, -8.2953190e+04,  2.0987555e+06,  3.6350600e+05,
       -1.2361429e+05,  6.4917570e+05,  2.9350420e+06,  4.6234090e+06,
        4.6234090e+05,  1.7718710e+05,  1.7790720e+06,  2.2779490e+05,
       -4.4203120e+04,  2.0937460e+05,  2.1211500e+06,  7.4885610e+05,
        1.3072361e+07,  6.2405020e+06,  7.5380480e+05,  4.2790640e+05,
        8.6987640e+05,  6.4917570e+06,  1.5595890e+07, -2.0937460e+04,
        1.5228530e+05,  4.6680900e+05,  1.9871970e+05,  8.8872680e+06,
        1.3930776e+07, -1.3965560e+04,  1.3975159e+06,  1.5595890e+06,
        2.6317100e+05, -1.3072361e+05,  2.0987555e+07, -7.6246510e+04,
       -4.1408670e+04,  4.6458940e+05,  1.1814116e+06, -6.0643250e+04,
       -1.1531600e+04, -2.1211500e+04,  1.7979549e+07,  1.4558980e+06,
       -7.2564100e+04,  2.0323890e+05,  7.8047800e+06,  5.1356920e+05,
        2.4762020e+05, -1.3617695e+05])

In [32]:
year_2015[
    year_2015['original_price_inr'].isna()
]

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating,duplicate_type,duplicate_flag
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,NaN,0.00,...,3.0,Delivered,1,2015,1,0.22,True,3.5,unique,False
39,TXN_2015_00000040,2015-01-17,CUST_2015_00002912,PROD_001710,Lenovo Tab M10 8GB RAM Black,Electronics,Tablets,Lenovo,NaN,0.00,...,NaN,Delivered,1,2015,1,0.49,True,4.1,unique,False
40,TXN_2015_00000041,2015-01-26,CUST_2015_00000352,PROD_001983,Samsung OLED TV,Electronics,TV & Entertainment,Samsung,NaN,38.43,...,3.0,Delivered,1,2015,1,25.87,False,3.9,unique,False
50,TXN_2015_00000051,2015-01-24,CUST_2015_00009276,PROD_000057,OnePlus OnePlus 2 64GB White,Electronics,Smartphones,OnePlus,NaN,36.33,...,4.5,Delivered,1,2015,1,0.22,True,4.6,unique,False
52,TXN_2015_00000053,2015-12-01,CUST_2015_00007293,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,NaN,0.00,...,4.0,Delivered,1,2015,1,0.17,True,3.3,unique,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33121,TXN_2015_00026661_DUP,2015-12-11,CUST_2015_00004102,PROD_000091,Motorola Moto G (3rd Gen) 64GB Blue,Electronics,Smartphones,Motorola,NaN,22.07,...,4.0,Delivered,11,2015,4,0.22,True,3.4,unique,True
33125,TXN_2015_00007374_DUP,2015-09-04,CUST_2015_00011692,PROD_000054,OnePlus OnePlus 2 64GB Black,Electronics,Smartphones,OnePlus,NaN,20.71,...,NaN,Delivered,4,2015,2,0.21,False,4.2,unique,True
33126,TXN_2015_00027631_DUP,2015-06-11,CUST_2015_00005657,PROD_000034,Samsung Galaxy S6 Edge 16GB Blue,Electronics,Smartphones,Samsung,NaN,0.00,...,4.5,Delivered,11,2015,4,0.18,True,3.3,unique,True
33133,TXN_2015_00004527_DUP,2015-10-03,CUST_2015_00001648,PROD_000065,Xiaomi Mi 4i 32GB Black,Electronics,Smartphones,Xiaomi,NaN,22.56,...,5.0,Returned,3,2015,1,0.16,True,4.5,unique,True
33154,TXN_2015_00030358_DUP,2015-12-29,CUST_2015_00008709,PROD_001949,Noise Watch Premium,Electronics,Smart Watch,Noise,NaN,23.88,...,4.0,Delivered,12,2015,4,0.07,True,4.3,unique,True

In [33]:
year_2015['original_price_inr'] = (
    year_2015['original_price_inr'].abs()
)

In [34]:
category_median = (
    year_2015
    .groupby('category')['original_price_inr']
    .transform('median')
)

In [35]:
mask_100x = (
    year_2015['original_price_inr']
    > category_median * 100
)

mask_10x = (
    year_2015['original_price_inr']
    > category_median * 10
)

In [36]:
# Fix 100x errors
year_2015.loc[
    mask_100x,
    'original_price_inr'
] = (
    year_2015.loc[
        mask_100x,
        'original_price_inr'
    ] / 100
)

# Fix 10x errors
year_2015.loc[
    (~mask_100x) & mask_10x,
    'original_price_inr'
] = (
    year_2015.loc[
        (~mask_100x) & mask_10x,
        'original_price_inr'
    ] / 10
)

In [37]:
#Q3 - column to contain only numeric values representing the rating.
year_2015['customer_rating'] = year_2015['customer_rating'].astype(str) # Convert to string for processing

year_2015['customer_rating'] = year_2015['customer_rating'].str.split('/').str[0] # Keep only the part before the slash

year_2015['customer_rating'] = year_2015['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present

year_2015['customer_rating'] = year_2015['customer_rating'].str.strip() # Remove any leading/trailing whitespace

year_2015['customer_rating'] = pd.to_numeric(year_2015['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [38]:
year_2015.loc[
    year_2015['original_price_inr']
    > category_median * 20,
    'original_price_inr'
] = category_median

In [39]:
year_2015['original_price_inr'] = (
    year_2015['original_price_inr']
    .fillna(category_median)
)

In [40]:
year_2015['original_price_inr'].describe()

count     33165.000000
mean      62131.703981
std       44422.603722
min        2374.840000
25%       28668.340000
50%       46458.940000
75%       86591.570000
max      464589.400000
Name: original_price_inr, dtype: float64

In [41]:
year_2015['original_price_inr'].max()

np.float64(464589.4)

In [42]:
year_2015['payment_method'].unique()

<StringArray>
['COD', 'Debit Card', 'Credit Card', 'Net Banking']
Length: 4, dtype: str

In [43]:


#customer city
year_2015['customer_city'].head(40)
year_2015['customer_city'].unique()

<StringArray>
[       'Mumbai',     'Allahabad',       'Kolkata',      'Ludhiana',
         'Delhi',       'Lucknow',        'Jaipur',   'Bhubaneswar',
     'Ahmedabad',     'Bangalore',          'Pune',         'Kochi',
       'Chennai',        'Nagpur', 'Visakhapatnam',         'mumba',
     'Gorakhpur',        'Bombay',        'Kanpur',    'Chandigarh',
     'Hyderabad',       'Aligarh',        'Indore',         'Patna',
        'Meerut',    'Coimbatore',      'Vadodara',    'Saharanpur',
      'Bareilly',     'BANGALORE',     'Moradabad',     'New Delhi',
         'Surat',       'KOLKATA',      'Banglore',        'Madras',
        'chenai',     'Delhi NCR',      'Varanasi',     'Bengalore',
     'Bengaluru',        'MUMBAI',      'Kolkata ',      'Calcutta',
         'delhi',       'CHENNAI',      'Chennai ',       'kolkata',
       'Mumbai ',         'DELHI']
Length: 50, dtype: str

In [44]:
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2015['customer_city'] = year_2015['customer_city'].replace(city_map)

year_2015['customer_city'] = year_2015['customer_city'].str.title()

In [45]:
year_2015['customer_city'].unique()

<StringArray>
[       'Mumbai',     'Allahabad',       'Kolkata',      'Ludhiana',
         'Delhi',       'Lucknow',        'Jaipur',   'Bhubaneswar',
     'Ahmedabad',     'Bengaluru',          'Pune',         'Kochi',
       'Chennai',        'Nagpur', 'Visakhapatnam',     'Gorakhpur',
        'Kanpur',    'Chandigarh',     'Hyderabad',       'Aligarh',
        'Indore',         'Patna',        'Meerut',    'Coimbatore',
      'Vadodara',    'Saharanpur',      'Bareilly',     'Bangalore',
     'Moradabad',         'Surat',        'Chenai',      'Varanasi']
Length: 32, dtype: str

In [46]:
year_2015['delivery_days'].value_counts()

delivery_days
4     10100
3      9762
5      6360
6      4820
7      1667
0       204
2       128
1        62
15       62
Name: count, dtype: int64

In [47]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date', 'final_amount_inr']

# Check number of duplicates
duplicate_count = year_2015.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2015 = year_2015.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2015.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 165
Duplicates after removal: 0

In [48]:


year_2015['original_price_inr'].describe()

count     33000.000000
mean      62113.047575
std       44408.137804
min        2374.840000
25%       28668.340000
50%       46458.940000
75%       86591.570000
max      464589.400000
Name: original_price_inr, dtype: float64

In [49]:


year_2015.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           2640
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         3960
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             22459
customer_rating            9926
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
duplicate_type                0
duplicate_flag                0
dtype: int64

In [50]:


year_2015['duplicate_flag'].value_counts()
year_2015['duplicate_type'].value_counts()

duplicate_type
unique    33000
Name: count, dtype: int64

In [51]:
year_2015 = year_2015.drop(
    columns=[
        'duplicate_flag',
        'duplicate_type'
    ],
    errors='ignore'
)

In [52]:
year_2015

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-05-01,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,46458.94,0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32995,TXN_2015_00032996,2015-12-16,CUST_2015_00005804,PROD_001733,OnePlus Galaxy Tab 4GB RAM Silver,Electronics,Tablets,OnePlus,46234.09,0.00,...,False,NaN,5.0,Delivered,12,2015,4,0.53,False,4.3
32996,TXN_2015_00032997,2015-12-30,CUST_2015_00011500,PROD_000051,Samsung Galaxy J7 32GB Blue,Electronics,Smartphones,Samsung,19871.97,0.00,...,False,NaN,NaN,Delivered,12,2015,4,0.19,True,4.3
32997,TXN_2015_00032998,2015-12-28,CUST_2015_00000632,PROD_000073,Xiaomi Redmi 2 16GB White,Electronics,Smartphones,Xiaomi,43767.40,28.40,...,False,NaN,5.0,Delivered,12,2015,4,0.23,True,4.2
32998,TXN_2015_00032999,2015-12-26,CUST_2015_00008830,PROD_001693,Samsung Galaxy Tab 8GB RAM Black,Electronics,Tablets,Samsung,73967.02,10.83,...,False,NaN,5.0,Delivered,12,2015,4,0.45,True,3.7
32999,TXN_2015_00033000,2015-07-12,CUST_2015_00006606,PROD_000073,Xiaomi Redmi 2 16GB White,Electronics,Smartphones,Xiaomi,43767.40,0.00,...,False,NaN,NaN,Delivered,12,2015,4,0.23,True,4.2

In [53]:
year_2015['customer_rating'] = (year_2015['customer_rating'].fillna(1))

In [54]:
year_2015['festival_name'] = (year_2015['festival_name'].fillna('Regular Sale'))

In [55]:
year_2015['customer_rating'].unique()

array([5. , 4.5, 1. , 3. , 4. , 3.5])

In [56]:
year_2015['original_price_inr'].describe()

count     33000.000000
mean      62113.047575
std       44408.137804
min        2374.840000
25%       28668.340000
50%       46458.940000
75%       86591.570000
max      464589.400000
Name: original_price_inr, dtype: float64

In [57]:
year_2015['delivery_charges'] = year_2015['delivery_charges'].fillna(0.0)

In [58]:
year_2015.isna().sum()

transaction_id               0
order_date                   0
customer_id                  0
product_id                   0
product_name                 0
category                     0
subcategory                  0
brand                        0
original_price_inr           0
discount_percent             0
discounted_price_inr         0
quantity                     0
subtotal_inr                 0
delivery_charges             0
final_amount_inr             0
customer_city                0
customer_state               0
customer_tier                0
customer_spending_tier       0
customer_age_group        3960
payment_method               0
delivery_days                0
delivery_type                0
is_prime_member              0
is_festival_sale             0
festival_name                0
customer_rating              0
return_status                0
order_month                  0
order_year                   0
order_quarter                0
product_weight_kg            0
is_prime_eligible            0
product_rating               0
dtype: int64

In [59]:
year_2015

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-05-01,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,Regular Sale,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,1.0,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,46458.94,0.00,...,False,Regular Sale,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,Regular Sale,4.0,Delivered,1,2015,1,0.20,True,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32995,TXN_2015_00032996,2015-12-16,CUST_2015_00005804,PROD_001733,OnePlus Galaxy Tab 4GB RAM Silver,Electronics,Tablets,OnePlus,46234.09,0.00,...,False,Regular Sale,5.0,Delivered,12,2015,4,0.53,False,4.3
32996,TXN_2015_00032997,2015-12-30,CUST_2015_00011500,PROD_000051,Samsung Galaxy J7 32GB Blue,Electronics,Smartphones,Samsung,19871.97,0.00,...,False,Regular Sale,1.0,Delivered,12,2015,4,0.19,True,4.3
32997,TXN_2015_00032998,2015-12-28,CUST_2015_00000632,PROD_000073,Xiaomi Redmi 2 16GB White,Electronics,Smartphones,Xiaomi,43767.40,28.40,...,False,Regular Sale,5.0,Delivered,12,2015,4,0.23,True,4.2
32998,TXN_2015_00032999,2015-12-26,CUST_2015_00008830,PROD_001693,Samsung Galaxy Tab 8GB RAM Black,Electronics,Tablets,Samsung,73967.02,10.83,...,False,Regular Sale,5.0,Delivered,12,2015,4,0.45,True,3.7
32999,TXN_2015_00033000,2015-07-12,CUST_2015_00006606,PROD_000073,Xiaomi Redmi 2 16GB White,Electronics,Smartphones,Xiaomi,43767.40,0.00,...,False,Regular Sale,1.0,Delivered,12,2015,4,0.23,True,4.2

In [60]:
year_2015['payment_method'].unique()

<StringArray>
['COD', 'Debit Card', 'Credit Card', 'Net Banking']
Length: 4, dtype: str

In [61]:
year_2015['customer_age_group'] = year_2015['customer_age_group'].fillna('Unknown')
year_2015 = year_2015.dropna(subset=['customer_rating'])

In [62]:
year_2015.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [63]:
year_2015['customer_rating'] = (year_2015['customer_rating'].replace(1, np.nan))

In [64]:
year_2015['customer_rating'].unique()

array([5. , 4.5, nan, 3. , 4. , 3.5])

In [65]:
year_2015.to_csv(
    '2015_cleaned.csv',
    index=False
)

In [66]:
year_2015.value_counts()

transaction_id     order_date  customer_id         product_id   product_name                          category     subcategory  brand      original_price_inr  discount_percent  discounted_price_inr  quantity  subtotal_inr  delivery_charges  final_amount_inr  customer_city  customer_state  customer_tier  customer_spending_tier  customer_age_group  payment_method  delivery_days  delivery_type  is_prime_member  is_festival_sale  festival_name      customer_rating  return_status  order_month  order_year  order_quarter  product_weight_kg  is_prime_eligible  product_rating
TXN_2015_00000001  2015-01-25  CUST_2015_00003884  PROD_000021  Samsung Galaxy S6 16GB Black          Electronics  Smartphones  Samsung    123614.29           27.91             89112.17              1         89112.17      0.0               89112.17          Mumbai         Maharashtra     Metro          Premium                 46-55               COD             6              Standard       False            True              Republic Day Sale  5.0              Delivered      1            2015        1              0.19               True               4.7               1
TXN_2015_00000002  2015-05-01  CUST_2015_00011709  PROD_000055  OnePlus OnePlus 2 16GB White          Electronics  Smartphones  OnePlus    54731.86            0.00              54731.86              1         54731.86      0.0               54731.86          Allahabad      Uttar Pradesh   Rural          Standard                26-35               COD             4              Standard       False            False             Regular Sale       4.5              Delivered      1            2015        1              0.20               True               4.1               1
TXN_2015_00000004  2015-01-28  CUST_2015_00008105  PROD_000085  Motorola Moto G (3rd Gen) 16GB Black  Electronics  Smartphones  Motorola   46458.94            0.00              21947.26              1         21947.26      0.0               21947.26          Kolkata        West Bengal     Metro          Budget                  36-45               COD             4              Standard       False            False             Regular Sale       3.0              Delivered      1            2015        1              0.22               True               3.5               1
TXN_2015_00000005  2015-01-31  CUST_2015_00002955  PROD_000055  OnePlus OnePlus 2 16GB White          Electronics  Smartphones  OnePlus    54731.86            0.00              54731.86              2         109463.72     0.0               109463.72         Ludhiana       Punjab          Tier2          Standard                18-25               COD             3              Standard       False            False             Regular Sale       4.0              Delivered      1            2015        1              0.20               True               4.1               1
TXN_2015_00000006  2015-04-01  CUST_2015_00006757  PROD_001665  Alienware MacBook 4GB RAM Black       Electronics  Laptops      Alienware  131194.65           0.00              131194.65             1         131194.65     0.0               131194.65         Delhi          Delhi           Metro          Standard                18-25               Debit Card      3              Standard       False            False             Regular Sale       4.5              Delivered      1            2015        1              1.39               False              3.6               1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
TXN_2015_00032993  2015-12-22  CUST_2015_00009977  PROD_000105  Motorola Moto E (2nd Gen) 64GB White  Electronics  Smartphones  Motorola   21211.50            0.00              21211.50              1         21211.50      0.0               21211.50          Surat          Gujarat         Tier1          Standard                26-35               Credit Card     3              Standard       False            False             Regular Sale       3.5              Delivered      12           2015        4              0.21               False              3.8               1
TXN_2015_00032994  2015-11-12  CUST_2015_00002010  PROD_000083  Xiaomi Redmi Note 4G 16GB Blue        Electronics  Smartphones  Xiaomi     33199.84            21.03             26219.01              3         78657.02      0.0               78657.02          Chennai        Tamil Nadu      Metro          Standard                26-35               COD             6              Standard       False            False             Regular Sale       4.5              Delivered      12           2015        4              0.15               False              4.1               1
TXN_2015_00032996  2015-12-16  CUST_2015_00005804  PROD_001733  OnePlus Galaxy Tab 4GB RAM Silver     Electronics  Tablets      OnePlus    46234.09            0.00              46234.09              2         92468.18      0.0               92468.18          Ahmedabad      Gujarat         Tier1          Standard                36-45               COD             6              Standard       False            False             Regular Sale       5.0              Delivered      12           2015        4              0.53               False              4.3               1
TXN_2015_00032998  2015-12-28  CUST_2015_00000632  PROD_000073  Xiaomi Redmi 2 16GB White             Electronics  Smartphones  Xiaomi     43767.40            28.40             31336.66              1         31336.66      0.0               31336.66          Mumbai         Maharashtra     Metro          Budget                  26-35               COD             6              Standard       False            False             Regular Sale       5.0              Delivered      12           2015        4              0.23               True               4.2               1
TXN_2015_00032999  2015-12-26  CUST_2015_00008830  PROD_001693  Samsung Galaxy Tab 8GB RAM Black      Electronics  Tablets      Samsung    73967.02            10.83             65957.94              1         65957.94      0.0               65957.94          Bengaluru      Karnataka       Metro          Standard                26-35               COD             4              Standard       False            False             Regular Sale       5.0              Delivered      12           2015        4              0.45               True               3.7               1
Name: count, Length: 23074, dtype: int64