In [1]:
import pandas as pd
import numpy as np

In [2]:
year_2018 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2018.csv")
year_2018

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2018_00000001,2018-01-28,CUST_2015_00011381,PROD_000367,Samsung Galaxy S9+ 128GB White,Electronics,Smartphones,Samsung,123828.89,0.00,...,False,NaN,4.5,Delivered,1,2018,1,0.21,False,3.9
1,TXN_2018_00000002,2018-01-09,CUST_2018_00004073,PROD_001683,Apple Mi Pad 8GB RAM Silver,Electronics,Tablets,Apple,61478.19,0.00,...,False,NaN,4.0,Delivered,1,2018,1,0.40,True,4.5
2,TXN_2018_00000003,2018-01-06,CUST_2018_00024729,PROD_001688,Apple Slate 8GB RAM Black,Electronics,Tablets,Apple,38624.59,0.00,...,False,NaN,4.5,Delivered,1,2018,1,0.41,True,3.2
3,TXN_2018_00000004,2018-01-20,CUST_2018_00015834,PROD_000236,Apple iPhone X 64GB Blue,Electronics,Smartphones,Apple,201630.77,47.20,...,True,Republic Day Sale,5.0,Delivered,1,2018,1,0.25,True,4.0
4,TXN_2018_00000005,2018-01-07,CUST_2016_00001228,PROD_000163,OnePlus OnePlus 3T 16GB Black,Electronics,Smartphones,OnePlus,53961.7,0.00,...,False,NaN,NaN,Delivered,1,2018,1,0.16,True,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99490,TXN_2018_00008489_DUP,2018-02-03,CUST_2018_00015525,PROD_001600,Acer MacBook 4GB RAM Black,Electronics,Laptops,Acer,70447.94,7.24,...,False,NaN,4.0,Delivered,2,2018,1,2.06,No,4.7
99491,TXN_2018_00081228_DUP,2018-11-28,CUST_2018_00019421,PROD_000193,Motorola Moto G4 32GB White,Electronics,Smartphones,Motorola,17421.69,29.06,...,False,NaN,4.0,Delivered,11,2018,4,0.16,True,3.5
99492,TXN_2018_00016498_DUP,2018-03-11,CUST_2017_00006834,PROD_001531,HP Gaming 8GB RAM Silver,Electronics,Laptops,HP,114816.88,62.15,...,True,Holi Festival,4/5,Delivered,3,2018,1,1.98,False,4.0
99493,TXN_2018_00082178_DUP,2018-11-03,CUST_2018_00016997,PROD_001943,Garmin Sports Watch Premium,Electronics,Smart Watch,Garmin,55879.27,34.43,...,Yes,Diwali Sale,4.0,Delivered,11,2018,4,0.07,True,4.2
99494,TXN_2018_00031555_DUP,2018-05-19,CUST_2016_00011269,PROD_000335,Oppo F3 Plus 32GB Blue,Electronics,Smartphones,Oppo,"37,966.48",0.00,...,False,NaN,NaN,Delivered,5,2018,2,0.19,True,4.5

In [3]:
year_2018.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'subcategory', 'brand',
       'original_price_inr', 'discount_percent', 'discounted_price_inr',
       'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
       'customer_city', 'customer_state', 'customer_tier',
       'customer_spending_tier', 'customer_age_group', 'payment_method',
       'delivery_days', 'delivery_type', 'is_prime_member', 'is_festival_sale',
       'festival_name', 'customer_rating', 'return_status', 'order_month',
       'order_year', 'order_quarter', 'product_weight_kg', 'is_prime_eligible',
       'product_rating'],
      dtype='str')

In [4]:


year_2018.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           7953
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        11939
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             67918
customer_rating           30234
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [40]:
year_2018.value_counts()

transaction_id     order_date  customer_id         product_id   product_name                       category     subcategory  brand    original_price_inr  discount_percent  discounted_price_inr  quantity  subtotal_inr  delivery_charges  final_amount_inr  customer_city  customer_state  customer_tier  customer_spending_tier  customer_age_group  payment_method  delivery_days  delivery_type  is_prime_member  is_festival_sale  festival_name      customer_rating  return_status  order_month  order_year  order_quarter  product_weight_kg  is_prime_eligible  product_rating
TXN_2018_00000001  2018-01-28  CUST_2015_00011381  PROD_000367  Samsung Galaxy S9+ 128GB White     Electronics  Smartphones  Samsung  123828.89           0.00              123828.89             1         123828.89     0.0               123828.89         Delhi          Delhi           Metro          Premium                 18-25               COD             3              Standard       False            False             Regular Sale       4.5              Delivered      1            2018        1              0.21               False              3.9               1
TXN_2018_00000002  2018-09-01  CUST_2018_00004073  PROD_001683  Apple Mi Pad 8GB RAM Silver        Electronics  Tablets      Apple    61478.19            0.00              61478.19              1         61478.19      0.0               61478.19          Mumbai         Maharashtra     Metro          Premium                 18-25               COD             3              Standard       True             False             Regular Sale       4.0              Delivered      1            2018        1              0.40               True               4.5               1
TXN_2018_00000003  2018-06-01  CUST_2018_00024729  PROD_001688  Apple Slate 8GB RAM Black          Electronics  Tablets      Apple    38624.59            0.00              38624.59              2         77249.18      0.0               77249.18          Kochi          Kerala          Tier2          Standard                26-35               Debit Card      4              Standard       False            False             Regular Sale       4.5              Delivered      1            2018        1              0.41               True               3.2               1
TXN_2018_00000004  2018-01-20  CUST_2018_00015834  PROD_000236  Apple iPhone X 64GB Blue           Electronics  Smartphones  Apple    201630.77           47.20             106459.69             1         106459.69     0.0               106459.69         Delhi          Delhi           Metro          Premium                 36-45               COD             4              Standard       False            True              Republic Day Sale  5.0              Delivered      1            2018        1              0.25               True               4.0               1
TXN_2018_00000005  2018-07-01  CUST_2016_00001228  PROD_000163  OnePlus OnePlus 3T 16GB Black      Electronics  Smartphones  OnePlus  53961.70            0.00              53961.70              1         53961.70      0.0               53961.70          Indore         Madhya Pradesh  Tier1          Premium                 18-25               COD             3              Standard       False            False             Regular Sale       1.0              Delivered      1            2018        1              0.16               True               4.7               1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
TXN_2018_00098994  2018-12-13  CUST_2018_00018859  PROD_001612  Apple Pavilion 8GB RAM Silver      Electronics  Laptops      Apple    65031.44            0.00              65031.44              1         65031.44      0.0               65031.44          Bengaluru      Karnataka       Metro          Standard                26-35               Credit Card     5              Standard       False            False             Regular Sale       5.0              Delivered      12           2018        4              2.69               True               3.7               1
TXN_2018_00098996  2018-12-18  CUST_2018_00034488  PROD_000273  OnePlus OnePlus 5T 16GB White      Electronics  Smartphones  OnePlus  99824.06            0.00              99824.06              1         99824.06      0.0               99824.06          Delhi          Delhi           Metro          Premium                 18-25               COD             4              Standard       False            False             Regular Sale       4.5              Delivered      12           2018        4              0.16               True               4.3               1
TXN_2018_00098998  2018-12-30  CUST_2018_00001867  PROD_000152  Samsung Galaxy J7 Prime 16GB Blue  Electronics  Smartphones  Samsung  32492.25            5.01              30865.52              1         30865.52      0.0               30865.52          Chennai        Tamil Nadu      Metro          Budget                  26-35               UPI             4              Standard       False            False             Regular Sale       4.0              Returned       12           2018        4              0.16               True               3.6               1
TXN_2018_00098999  2018-06-12  CUST_2017_00007517  PROD_000167  OnePlus OnePlus 3T 64GB White      Electronics  Smartphones  OnePlus  96344.00            19.46             77597.94              1         77597.94      0.0               77597.94          Delhi          Delhi           Metro          Standard                36-45               COD             6              Standard       False            False             Regular Sale       4.5              Delivered      12           2018        4              0.24               True               3.5               1
TXN_2018_00099000  2018-07-12  CUST_2018_00030094  PROD_001603  Acer Gaming 8GB RAM Silver         Electronics  Laptops      Acer     151060.56           17.09             125240.60             1         125240.60     0.0               125240.60         Pune           Maharashtra     Tier1          Standard                26-35               COD             5              Standard       False            False             Regular Sale       1.0              Delivered      12           2018        4              2.27               True               4.6               1
Name: count, Length: 87120, dtype: int64

In [5]:
year_2018['delivery_charges'] = year_2018['delivery_charges'].fillna(0.0)

In [6]:
year_2018.duplicated().sum()

np.int64(0)

In [7]:
year_2018['order_date'].isna().sum()

np.int64(0)

In [8]:
#Q1 datetime format 

year_2018['order_date'] = pd.to_datetime(
    year_2018['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2018['order_date'].dropna().median()

year_2018['order_date'] = (
    year_2018['order_date']
    .fillna(median_date)
)

# Standardize format
year_2018['order_date'] = (
    year_2018['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [9]:
year_2018['order_date'].head()

0    2018-01-28
1    2018-09-01
2    2018-06-01
3    2018-01-20
4    2018-07-01
Name: order_date, dtype: str

In [10]:
year_2018['original_price_inr'].iloc[16:45]

16    246998.55
17     49034.97
18     55879.27
19     29251.66
20     48472.48
21     220349.8
22     31018.55
23    87,376.17
24     67330.08
25     45538.49
26    104592.57
27     43643.13
28     27386.87
29     40785.59
30     40339.02
31     27697.63
32     32897.14
33     88185.11
34     77485.49
35     25970.76
36      35455.6
37     29218.96
38     59911.01
39     44394.59
40     19361.79
41    105662.74
42      47591.2
43     92366.92
44      37393.2
Name: original_price_inr, dtype: str

In [11]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2018['original_price_inr'] = year_2018['original_price_inr'].str.replace('₹', '', regex=False)
year_2018['original_price_inr'] = year_2018['original_price_inr'].str.replace('Rs', '', regex=False)
year_2018['original_price_inr'] = year_2018['original_price_inr'].str.replace(',', '', regex=False)
year_2018['original_price_inr'] = year_2018['original_price_inr'].astype(float)

year_2018['original_price_inr'].iloc[16:45]

16    246998.55
17     49034.97
18     55879.27
19     29251.66
20     48472.48
21    220349.80
22     31018.55
23     87376.17
24     67330.08
25     45538.49
26    104592.57
27     43643.13
28     27386.87
29     40785.59
30     40339.02
31     27697.63
32     32897.14
33     88185.11
34     77485.49
35     25970.76
36     35455.60
37     29218.96
38     59911.01
39     44394.59
40     19361.79
41    105662.74
42     47591.20
43     92366.92
44     37393.20
Name: original_price_inr, dtype: float64

In [12]:
year_2018['original_price_inr']

0        123828.89
1         61478.19
2         38624.59
3        201630.77
4         53961.70
           ...
99490     70447.94
99491     17421.69
99492    114816.88
99493     55879.27
99494     37966.48
Name: original_price_inr, Length: 99495, dtype: float64

In [13]:
year_2018['customer_rating'].value_counts()

customer_rating
4.5          21716
5.0          16544
4.0          15310
3.5           6578
3.0           3583
4/5            920
4.5 stars      728
5.0 stars      614
4.0 stars      498
5/5            436
4.5/5.0        397
4              330
3/5            296
5.0/5.0        294
4.0/5.0        262
3.5 stars      237
5              150
3              104
3.5/5.0        101
3.0 stars       98
3.0/5.0         65
Name: count, dtype: int64

In [14]:
#Q3 - column to contain only numeric values representing the rating.
year_2018['customer_rating'] = year_2018['customer_rating'].astype(str) # Convert to string for processing
year_2018['customer_rating'] = year_2018['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2018['customer_rating'] = year_2018['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2018['customer_rating'] = year_2018['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2018['customer_rating'] = pd.to_numeric(year_2018['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [15]:
year_2018['customer_city'].unique()

<StringArray>
[        'Delhi',        'Mumbai',         'Kochi',        'Indore',
     'Bangalore',        'Kanpur',     'Hyderabad',      'Ludhiana',
    'Chandigarh', 'Visakhapatnam',          'Pune',         'Surat',
       'Lucknow',    'Saharanpur',    'Coimbatore',        'Jaipur',
       'Mumbai ',     'Ahmedabad',       'Kolkata',       'Chennai',
        'Nagpur',         'Patna',   'Bhubaneswar',      'Vadodara',
       'Aligarh',        'Bombay',     'Moradabad',        'Meerut',
      'Varanasi',     'Gorakhpur',        'Madras',     'Bengaluru',
      'Bareilly',      'Kolkata ',     'Delhi NCR',     'BANGALORE',
       'KOLKATA',         'delhi',     'Allahabad',      'Banglore',
       'CHENNAI',      'Chennai ',         'mumba',        'chenai',
      'Calcutta',     'Bengalore',     'New Delhi',       'kolkata',
        'MUMBAI',         'DELHI']
Length: 50, dtype: str

In [32]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2018['customer_city'] = year_2018['customer_city'].replace(city_map)

year_2018['customer_city'] = year_2018['customer_city'].str.title()
year_2018['customer_city'].unique()

<StringArray>
[        'Delhi',        'Mumbai',         'Kochi',        'Indore',
     'Bengaluru',        'Kanpur',     'Hyderabad',      'Ludhiana',
    'Chandigarh', 'Visakhapatnam',          'Pune',         'Surat',
       'Lucknow',    'Saharanpur',    'Coimbatore',        'Jaipur',
     'Ahmedabad',       'Kolkata',       'Chennai',        'Nagpur',
         'Patna',   'Bhubaneswar',      'Vadodara',       'Aligarh',
     'Moradabad',        'Meerut',      'Varanasi',     'Gorakhpur',
      'Bareilly',     'Allahabad']
Length: 30, dtype: str

In [33]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2018[col] = year_2018[col].map(bool_map)

In [34]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2018['category'] = (
    year_2018['category']
    .replace(category_map)
)

In [35]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2018['delivery_days'] = year_2018['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2018['delivery_days'] = pd.to_numeric(
    year_2018['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2018.loc[
    (year_2018['delivery_days'] >= 0) &
    (year_2018['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2018.loc[
    (year_2018['delivery_days'] < 0) |
    (year_2018['delivery_days'] > 30) |
    (year_2018['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2018['delivery_days'] = year_2018['delivery_days'].astype(int)

In [20]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date', 'final_amount_inr']

# Check number of duplicates
duplicate_count = year_2018.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2018 = year_2018.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2018.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 495
Duplicates after removal: 0

In [21]:
year_2018['original_price_inr'].describe()

count    9.900000e+04
mean     8.711622e+04
std      4.155844e+05
min     -2.515271e+05
25%      3.101855e+04
50%      4.873308e+04
75%      1.045926e+05
max      2.423711e+07
Name: original_price_inr, dtype: float64

In [22]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [23]:
#Q9 - column to contain the base price of the product in 2018.
year_2018 = year_2018.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2018['price_ratio'] = year_2018['original_price_inr'] / year_2018['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2018['price_ratio'] < 0.3) | (year_2018['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2018.loc[mask, 'original_price_inr'] = year_2018['base_price_2015'] # Replace outliers with base price
year_2018.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [24]:
year_2018['original_price_inr'].describe()

count     99000.000000
mean      70647.277401
std       52127.382524
min        1780.580000
25%       31018.550000
50%       48593.420000
75%      104347.980000
max      302960.800000
Name: original_price_inr, dtype: float64

In [39]:
year_2018['festival_name'].unique()

<StringArray>
[                'Regular Sale',            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [42]:
year_2018.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        11880
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name                 0
customer_rating           30061
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [27]:
year_2018['customer_rating'].unique()

array([4.5, 4. , 5. , nan, 3.5, 3. ])

In [28]:
year_2018['customer_rating'] = (year_2018['customer_rating'].fillna(1))

In [29]:
year_2018['festival_name'] = (year_2018['festival_name'].fillna('Regular Sale'))

In [30]:
year_2018.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        11880
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name                 0
customer_rating               0
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [38]:
#Q10 - payment method distribution.
year_2018['payment_method'].value_counts()

payment_method
COD            49466
Credit Card    16798
Debit Card     13920
UPI            12837
Net Banking     5979
Name: count, dtype: int64

In [44]:
year_2018['customer_age_group'] = year_2018['customer_age_group'].fillna('Unknown')
year_2018 = year_2018.dropna(subset=['customer_rating'])

In [41]:
year_2018['customer_rating'] = (year_2018['customer_rating'].replace(1, np.nan))

In [45]:
year_2018.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [46]:
year_2018.to_csv(
    '2018_cleaned.csv',
    index=False
)

In [37]:
year_2018

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2018_00000001,2018-01-28,CUST_2015_00011381,PROD_000367,Samsung Galaxy S9+ 128GB White,Electronics,Smartphones,Samsung,123828.89,0.00,...,False,Regular Sale,4.5,Delivered,1,2018,1,0.21,False,3.9
1,TXN_2018_00000002,2018-09-01,CUST_2018_00004073,PROD_001683,Apple Mi Pad 8GB RAM Silver,Electronics,Tablets,Apple,61478.19,0.00,...,False,Regular Sale,4.0,Delivered,1,2018,1,0.40,True,4.5
2,TXN_2018_00000003,2018-06-01,CUST_2018_00024729,PROD_001688,Apple Slate 8GB RAM Black,Electronics,Tablets,Apple,38624.59,0.00,...,False,Regular Sale,4.5,Delivered,1,2018,1,0.41,True,3.2
3,TXN_2018_00000004,2018-01-20,CUST_2018_00015834,PROD_000236,Apple iPhone X 64GB Blue,Electronics,Smartphones,Apple,201630.77,47.20,...,True,Republic Day Sale,5.0,Delivered,1,2018,1,0.25,True,4.0
4,TXN_2018_00000005,2018-07-01,CUST_2016_00001228,PROD_000163,OnePlus OnePlus 3T 16GB Black,Electronics,Smartphones,OnePlus,53961.70,0.00,...,False,Regular Sale,1.0,Delivered,1,2018,1,0.16,True,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98995,TXN_2018_00098996,2018-12-18,CUST_2018_00034488,PROD_000273,OnePlus OnePlus 5T 16GB White,Electronics,Smartphones,OnePlus,99824.06,0.00,...,False,Regular Sale,4.5,Delivered,12,2018,4,0.16,True,4.3
98996,TXN_2018_00098997,2018-04-12,CUST_2018_00035853,PROD_001677,Apple Galaxy Tab 4GB RAM Silver,Electronics,Tablets,Apple,76298.72,0.00,...,False,Regular Sale,4.0,Delivered,12,2018,4,0.34,True,3.8
98997,TXN_2018_00098998,2018-12-30,CUST_2018_00001867,PROD_000152,Samsung Galaxy J7 Prime 16GB Blue,Electronics,Smartphones,Samsung,32492.25,5.01,...,False,Regular Sale,4.0,Returned,12,2018,4,0.16,True,3.6
98998,TXN_2018_00098999,2018-06-12,CUST_2017_00007517,PROD_000167,OnePlus OnePlus 3T 64GB White,Electronics,Smartphones,OnePlus,96344.00,19.46,...,False,Regular Sale,4.5,Delivered,12,2018,4,0.24,True,3.5
98999,TXN_2018_00099000,2018-07-12,CUST_2018_00030094,PROD_001603,Acer Gaming 8GB RAM Silver,Electronics,Laptops,Acer,151060.56,17.09,...,False,Regular Sale,1.0,Delivered,12,2018,4,2.27,True,4.6