In [4]:
import pandas as pd
import numpy as np

In [5]:
year_2019 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2019.csv")
year_2019

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2019_00000001,2019-01-05,CUST_2019_00037860,PROD_001930,Fitbit Sports Watch Premium,Electronics,Smart Watch,Fitbit,29122.09,0.00,...,False,NaN,3.0,Delivered,1,2019,1,0.06,True,3.4
1,TXN_2019_00000002,2019-01-09,CUST_2019_00002481,PROD_001683,Apple Mi Pad 8GB RAM Silver,Electronics,Tablets,Apple,66396.45,0.00,...,False,NaN,3.5,Delivered,1,2019,1,0.40,True,4.5
2,TXN_2019_00000003,01/02/2019,CUST_2018_00031347,PROD_000460,Oppo F9 64GB Black,Electronics,Smartphones,Oppo,29966.28,0.00,...,False,NaN,5.0,Delivered,1,2019,1,0.16,True,3.3
3,TXN_2019_00000004,2019-01-22,CUST_2019_00024783,PROD_000633,Oppo Reno 64GB White,Electronics,Smartphones,Oppo,34225.21,19.68,...,True,Republic Day Sale,4.5,Delivered,1,2019,1,0.20,True,3.3
4,TXN_2019_00000005,2019-01-31,CUST_2019_00018471,PROD_000571,Xiaomi Mi A3 256GB Blue,Electronics,Smartphones,Xiaomi,27092.49,0.00,...,False,NaN,NaN,Returned,1,2019,1,0.25,True,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121600,TXN_2019_00099999_DUP,2019-11-19,CUST_2018_00006220,PROD_000347,Apple iPhone XS 64GB Blue,Electronics,Smartphones,Apple,149833.69,0.00,...,False,NaN,NaN,Delivered,11,2019,4,0.21,True,4.3
121601,TXN_2019_00116598_DUP,2019-12-12,CUST_2019_00042574,PROD_001745,Realme Tab M10 4GB RAM Silver,Electronics,Tablets,Realme,36655.57,0.00,...,False,NaN,5.0,Delivered,12,2019,4,0.57,True,3.1
121602,TXN_2019_00106497_DUP,2019-11-05,CUST_2015_00010945,PROD_000084,Xiaomi Redmi Note 4G 32GB Blue,Electronics,Smartphones,Xiaomi,33240.58,68.83,...,True,Diwali Sale,4.0,Delivered,11,2019,4,0.19,True,4.2
121603,TXN_2019_00027813_DUP,2019-04-13,CUST_2016_00011885,PROD_000061,OnePlus OnePlus X 32GB White,Electronics,Smartphones,OnePlus,"88,975.63",23.47,...,False,NaN,NaN,Delivered,4,2019,2,0.19,True,3.6
121604,TXN_2019_00034264_DUP,2019-05-27,CUST_2019_00030690,PROD_000490,Apple iPhone 11 Pro 256GB Black,Electronics,Smartphones,Apple,134188.14,0.00,...,FALSE,NaN,4.5,Delivered,5,2019,2,0.19,True,4.3

In [6]:


year_2019.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           9721
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        14595
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             82822
customer_rating           36793
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [7]:
year_2019['delivery_charges'] = year_2019['delivery_charges'].fillna(0.0)

In [8]:
year_2019.duplicated().sum()

np.int64(0)

In [9]:
year_2019['order_date'].isna().sum()

np.int64(0)

In [10]:
#Q1 datetime format 

year_2019['order_date'] = pd.to_datetime(
    year_2019['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2019['order_date'].dropna().median()

year_2019['order_date'] = (
    year_2019['order_date']
    .fillna(median_date)
)

# Standardize format
year_2019['order_date'] = (
    year_2019['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [41]:
year_2019['order_date'].iloc[15:50]

15    2019-08-01
16    2019-01-29
17    2019-04-01
18    2019-05-01
19    2019-01-16
20    2019-01-29
21    2019-10-01
22    2019-01-01
23    2019-03-01
24    2019-01-29
25    2019-01-23
26    2019-01-16
27    2019-01-22
28    2019-01-28
29    2019-01-31
30    2019-01-14
31    2019-01-29
32    2019-06-01
33    2019-01-27
34    2019-01-13
35    2019-01-13
36    2019-12-01
37    2019-01-28
38    2019-01-15
39    2019-02-01
40    2019-12-01
41    2019-01-16
42    2019-05-01
43    2019-01-25
44    2019-09-01
45    2019-01-24
46    2019-01-05
47    2019-06-01
48    2019-08-01
49    2019-01-31
Name: order_date, dtype: str

In [11]:
year_2019['order_date'].head()

0    2019-05-01
1    2019-09-01
2    2019-02-01
3    2019-01-22
4    2019-01-31
Name: order_date, dtype: str

In [12]:
year_2019['original_price_inr'].iloc[16:45]

16      100856.23
17      Rs 52,952
18        5170.68
19      114546.72
20    ₹104,006.00
21      140016.12
22     ₹30,027.43
23      125245.74
24      111193.36
25       94538.35
26       44610.08
27      110200.28
28       65832.54
29       94455.52
30       64703.89
31       48358.43
32       41311.13
33      185047.03
34       82173.11
35      102950.86
36       34077.57
37       77832.28
38       103023.9
39      133174.92
40      143435.64
41      143435.64
42       26745.31
43      143435.64
44      116549.32
Name: original_price_inr, dtype: str

In [13]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2019['original_price_inr'] = year_2019['original_price_inr'].str.replace('₹', '', regex=False)
year_2019['original_price_inr'] = year_2019['original_price_inr'].str.replace('Rs', '', regex=False)
year_2019['original_price_inr'] = year_2019['original_price_inr'].str.replace(',', '', regex=False)
year_2019['original_price_inr'] = year_2019['original_price_inr'].astype(float)

year_2019['original_price_inr'].iloc[16:45]

16    100856.23
17     52952.00
18      5170.68
19    114546.72
20    104006.00
21    140016.12
22     30027.43
23    125245.74
24    111193.36
25     94538.35
26     44610.08
27    110200.28
28     65832.54
29     94455.52
30     64703.89
31     48358.43
32     41311.13
33    185047.03
34     82173.11
35    102950.86
36     34077.57
37     77832.28
38    103023.90
39    133174.92
40    143435.64
41    143435.64
42     26745.31
43    143435.64
44    116549.32
Name: original_price_inr, dtype: float64

In [14]:
year_2019['original_price_inr']

0          29122.09
1          66396.45
2          29966.28
3          34225.21
4          27092.49
            ...
121600    149833.69
121601     36655.57
121602     33240.58
121603     88975.63
121604    134188.14
Name: original_price_inr, Length: 121605, dtype: float64

In [15]:
year_2019['customer_rating'].value_counts()

customer_rating
4.5          26787
5.0          20087
4.0          18789
3.5           8096
3.0           4268
4/5           1201
4.5 stars      924
5.0 stars      699
4.0 stars      636
5/5            507
4.5/5.0        441
4              405
5.0/5.0        343
4.0/5.0        324
3/5            314
3.5 stars      294
5              184
3.0 stars      176
3.5/5.0        145
3              109
3.0/5.0         83
Name: count, dtype: int64

In [16]:
#Q3 - column to contain only numeric values representing the rating.
year_2019['customer_rating'] = year_2019['customer_rating'].astype(str) # Convert to string for processing
year_2019['customer_rating'] = year_2019['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2019['customer_rating'] = year_2019['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2019['customer_rating'] = year_2019['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2019['customer_rating'] = pd.to_numeric(year_2019['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [34]:
year_2019['customer_rating'].value_counts()

customer_rating
1.0    36619
4.5    28016
5.0    21701
4.0    21247
3.5     8492
3.0     4925
Name: count, dtype: int64

In [17]:
year_2019['customer_city'].unique()

<StringArray>
[      'Kolkata',     'Bangalore',       'Lucknow',        'Kanpur',
        'Indore',        'Nagpur',         'Delhi',        'Mumbai',
         'Patna',        'Jaipur',    'Saharanpur',      'Vadodara',
         'Kochi', 'Visakhapatnam',      'Bareilly',     'Moradabad',
         'Surat',     'Ahmedabad',       'Chennai',     'Hyderabad',
   'Bhubaneswar',    'Chandigarh',          'Pune',      'Ludhiana',
    'Coimbatore',     'Gorakhpur',     'Allahabad',        'Meerut',
        'Madras',       'Aligarh',      'Varanasi',       'CHENNAI',
       'kolkata',      'Chennai ',     'New Delhi',        'chenai',
       'KOLKATA',       'Mumbai ',         'mumba',        'MUMBAI',
         'DELHI',      'Calcutta',     'Delhi NCR',      'Kolkata ',
        'Bombay',     'Bengaluru',     'Bengalore',     'BANGALORE',
         'delhi',      'Banglore']
Length: 50, dtype: str

In [35]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2019['customer_city'] = year_2019['customer_city'].replace(city_map)

year_2019['customer_city'] = year_2019['customer_city'].str.title()
year_2019['customer_city'].unique()

<StringArray>
[      'Kolkata',     'Bengaluru',       'Lucknow',        'Kanpur',
        'Indore',        'Nagpur',         'Delhi',        'Mumbai',
         'Patna',        'Jaipur',    'Saharanpur',      'Vadodara',
         'Kochi', 'Visakhapatnam',      'Bareilly',     'Moradabad',
         'Surat',     'Ahmedabad',       'Chennai',     'Hyderabad',
   'Bhubaneswar',    'Chandigarh',          'Pune',      'Ludhiana',
    'Coimbatore',     'Gorakhpur',     'Allahabad',        'Meerut',
       'Aligarh',      'Varanasi']
Length: 30, dtype: str

In [19]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2019[col] = year_2019[col].map(bool_map)

In [36]:
year_2019[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0            False               True             False
1             True               True             False
2             True               True             False
3             True               True              True
4            False               True             False

In [20]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2019['category'] = (
    year_2019['category']
    .replace(category_map)
)

In [37]:
year_2019['category'].value_counts()

category
Electronics    121000
Name: count, dtype: int64

In [38]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2019['delivery_days'] = year_2019['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2019['delivery_days'] = pd.to_numeric(
    year_2019['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2019.loc[
    (year_2019['delivery_days'] >= 0) &
    (year_2019['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2019.loc[
    (year_2019['delivery_days'] < 0) |
    (year_2019['delivery_days'] > 30) |
    (year_2019['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2019['delivery_days'] = year_2019['delivery_days'].astype(int)

In [39]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2019.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2019 = year_2019.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2019.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 0
Duplicates after removal: 0

In [40]:
year_2019['original_price_inr'].describe()

count    121000.000000
mean      68935.288345
std       50298.203245
min        2134.210000
25%       30926.950000
50%       46844.200000
75%      100767.220000
max      287334.400000
Name: original_price_inr, dtype: float64

In [24]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [25]:
#Q9 - column to contain the base price of the product in 2019.
year_2019 = year_2019.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2019['price_ratio'] = year_2019['original_price_inr'] / year_2019['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2019['price_ratio'] < 0.3) | (year_2019['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2019.loc[mask, 'original_price_inr'] = year_2019['base_price_2015'] # Replace outliers with base price
year_2019.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [26]:
year_2019['original_price_inr'].describe()

count    121000.000000
mean      68935.288345
std       50298.203245
min        2134.210000
25%       30926.950000
50%       46844.200000
75%      100767.220000
max      287334.400000
Name: original_price_inr, dtype: float64

In [27]:
year_2019['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [28]:
year_2019.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        14520
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             82420
customer_rating           36619
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [29]:
year_2019['customer_rating'].unique()

array([3. , 3.5, 5. , 4.5, nan, 4. ])

In [30]:
year_2019['customer_rating'] = (year_2019['customer_rating'].fillna(1))

In [31]:
year_2019['festival_name'] = (year_2019['festival_name'].fillna('Regular Sale'))

In [46]:
year_2019['customer_age_group'] = year_2019['customer_age_group'].fillna('Unknown')
year_2019 = year_2019.dropna(subset=['customer_rating'])

In [47]:
year_2019.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [43]:
year_2019['customer_rating'] = (year_2019['customer_rating'].replace(1, np.nan))

In [48]:
year_2019.to_csv(
    '2019_cleaned.csv',
    index=False
)