In [1]:
import pandas as pd
import numpy as np

In [2]:
year_2020 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2020.csv")
year_2020

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2020_00000001,2020-01-19,CUST_2020_00001031,PROD_000402,Xiaomi Poco F1 128GB Blue,Electronics,Smartphones,Xiaomi,36202.67,7.11,...,False,NaN,4.5,Cancelled,1,2020,1,0.19,False,3.4
1,TXN_2020_00000002,2020-01-19,CUST_2018_00013266,PROD_000486,Apple iPhone 11 128GB Blue,Electronics,Smartphones,Apple,165163.92,0.00,...,False,NaN,NaN,Returned,1,2020,1,0.19,True,4.3
2,TXN_2020_00000003,2020-01-17,CUST_2020_00001673,PROD_000278,Xiaomi Redmi 4A 16GB White,Electronics,Smartphones,Xiaomi,32906.94,0.00,...,False,NaN,5.0,Delivered,1,2020,1,0.21,True,4.1
3,TXN_2020_00000004,2020-01-25,CUST_2020_00026212,PROD_000245,Samsung Galaxy S8+ 32GB Black,Electronics,Smartphones,Samsung,136675.37,45.87,...,True,Republic Day Sale,4.5,Delivered,1,2020,1,0.23,True,3.8
4,TXN_2020_00000005,2020-01-01,CUST_2015_00009980,PROD_000765,Vivo V20 64GB Black,Electronics,Smartphones,Vivo,30041.81,0.00,...,False,NaN,4.0,Delivered,1,2020,1,0.23,False,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143710,TXN_2020_00080175_DUP,2020-08-14,CUST_2020_00007573,PROD_001743,Realme Galaxy Tab 8GB RAM Silver,Electronics,Tablets,Realme,75266.67,0.00,...,False,NaN,4.0,Returned,8,2020,3,0.67,True,4.0
143711,TXN_2020_00010237_DUP,2020-01-18,CUST_2016_00002366,PROD_000304,Vivo V7+ 32GB Blue,Electronics,Smartphones,Vivo,34469.39,0.00,...,False,NaN,3.5,Returned,1,2020,1,0.22,True,4.0
143712,TXN_2020_00038556_DUP,2020-04-23,CUST_2020_00045892,PROD_000255,Samsung Galaxy J7 Max 32GB Black,Electronics,Smartphones,Samsung,34026.05,0.00,...,False,NaN,NaN,Delivered,4,2020,2,0.16,False,4.7
143713,TXN_2020_00034749_DUP,2020-04-16,CUST_2020_00023707,PROD_001531,HP Gaming 8GB RAM Silver,Electronics,Laptops,HP,136596.96,0.00,...,False,NaN,4.0,Delivered,4,2020,2,1.98,False,4.0
143714,TXN_2020_00044212_DUP,2020-05-08,CUST_2018_00028657,PROD_000443,Vivo V11 128GB White,Electronics,Smartphones,Vivo,49003.32,33.74,...,True,Summer Sale,NaN,Delivered,5,2020,2,0.20,True,4.0

In [3]:


year_2020.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges          11518
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        17244
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             99915
customer_rating           43625
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [4]:
year_2020['delivery_charges'] = year_2020['delivery_charges'].fillna(0.0)

In [5]:
year_2020.duplicated().sum()

np.int64(0)

In [6]:
year_2020['order_date'].isna().sum()

np.int64(0)

In [7]:
#Q1 datetime format 

year_2020['order_date'] = pd.to_datetime(
    year_2020['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2020['order_date'].dropna().median()

year_2020['order_date'] = (
    year_2020['order_date']
    .fillna(median_date)
)

# Standardize format
year_2020['order_date'] = (
    year_2020['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [8]:
year_2020['order_date'].iloc[15:50]

15    2020-01-15
16    2020-05-01
17    2020-01-14
18    2020-06-01
19    2020-08-01
20    2020-01-16
21    2020-02-01
22    2020-01-21
23    2020-01-26
24    2020-01-17
25    2020-01-24
26    2020-11-01
27    2020-01-28
28    2020-03-01
29    2020-01-23
30    2020-09-01
31    2020-01-18
32    2020-10-01
33    2020-01-30
34    2020-04-01
35    2020-01-18
36    2020-01-31
37    2020-01-07
38    2020-02-01
39    2020-01-30
40    2020-06-01
41    2020-01-27
42    2020-05-01
43    2020-01-27
44    2020-06-01
45    2020-01-24
46    2020-03-01
47    2020-01-31
48    2020-06-01
49    2020-01-15
Name: order_date, dtype: str

In [10]:
year_2020['original_price_inr'].iloc[16:45]

16       29935.32
17    ₹211,304.52
18      156946.28
19       49163.92
20      227743.93
21       15104.16
22      172754.49
23      -67413.39
24        28547.1
25       44554.25
26       76864.44
27       67110.69
28       26428.45
29      126433.24
30      106756.21
31       49434.76
32       44412.63
33       35224.12
34       44243.09
35       36495.34
36       30908.19
37      113925.85
38       101460.0
39       28153.75
40      274094.96
41      Rs 54,446
42      117857.21
43      127350.13
44       44156.98
Name: original_price_inr, dtype: str

In [11]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2020['original_price_inr'] = year_2020['original_price_inr'].str.replace('₹', '', regex=False)
year_2020['original_price_inr'] = year_2020['original_price_inr'].str.replace('Rs', '', regex=False)
year_2020['original_price_inr'] = year_2020['original_price_inr'].str.replace(',', '', regex=False)
year_2020['original_price_inr'] = year_2020['original_price_inr'].astype(float)

year_2020['original_price_inr'].iloc[16:45]

16     29935.32
17    211304.52
18    156946.28
19     49163.92
20    227743.93
21     15104.16
22    172754.49
23    -67413.39
24     28547.10
25     44554.25
26     76864.44
27     67110.69
28     26428.45
29    126433.24
30    106756.21
31     49434.76
32     44412.63
33     35224.12
34     44243.09
35     36495.34
36     30908.19
37    113925.85
38    101460.00
39     28153.75
40    274094.96
41     54446.00
42    117857.21
43    127350.13
44     44156.98
Name: original_price_inr, dtype: float64

In [12]:
year_2020['original_price_inr']

0          36202.67
1         165163.92
2          32906.94
3         136675.37
4          30041.81
            ...
143710     75266.67
143711     34469.39
143712     34026.05
143713    136596.96
143714     49003.32
Name: original_price_inr, Length: 143715, dtype: float64

In [13]:
year_2020['customer_rating'].value_counts()

customer_rating
4.5          31600
5.0          23559
4.0          22064
3.5           9762
3.0           5107
4/5           1426
4.5 stars     1105
5.0 stars      819
4.0 stars      796
5/5            597
4.5/5.0        546
4              472
5.0/5.0        457
3/5            358
4.0/5.0        356
3.5 stars      325
5              210
3.0 stars      174
3.5/5.0        156
3              115
3.0/5.0         86
Name: count, dtype: int64

In [14]:
#Q3 - column to contain only numeric values representing the rating.
year_2020['customer_rating'] = year_2020['customer_rating'].astype(str) # Convert to string for processing
year_2020['customer_rating'] = year_2020['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2020['customer_rating'] = year_2020['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2020['customer_rating'] = year_2020['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2020['customer_rating'] = pd.to_numeric(year_2020['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [15]:
year_2020['customer_rating'].value_counts()

customer_rating
4.5    33251
5.0    25642
4.0    25114
3.5    10243
3.0     5840
Name: count, dtype: int64

In [16]:
year_2020['customer_city'].unique()

<StringArray>
[        'Delhi',     'Ahmedabad',       'Chennai',   'Bhubaneswar',
     'Bangalore',         'Patna',        'Mumbai',    'Coimbatore',
       'Lucknow',       'Kolkata',        'Indore',     'Hyderabad',
      'Vadodara',          'Pune', 'Visakhapatnam',        'Jaipur',
      'Bareilly',        'Kanpur',      'Ludhiana',        'Meerut',
    'Saharanpur',        'Nagpur',         'Surat',    'Chandigarh',
     'Gorakhpur',         'Kochi',      'Varanasi',     'Allahabad',
     'Moradabad',       'Aligarh',     'New Delhi',       'KOLKATA',
      'Banglore',         'delhi',       'kolkata',       'CHENNAI',
       'Mumbai ',     'Delhi NCR',        'MUMBAI',         'mumba',
      'Calcutta',     'Bengaluru',        'Bombay',        'chenai',
         'DELHI',      'Kolkata ',      'Chennai ',     'Bengalore',
        'Madras',     'BANGALORE']
Length: 50, dtype: str

In [18]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2020['customer_city'] = year_2020['customer_city'].replace(city_map)

year_2020['customer_city'] = year_2020['customer_city'].str.title()
year_2020['customer_city'].unique()

<StringArray>
[        'Delhi',     'Ahmedabad',       'Chennai',   'Bhubaneswar',
     'Bengaluru',         'Patna',        'Mumbai',    'Coimbatore',
       'Lucknow',       'Kolkata',        'Indore',     'Hyderabad',
      'Vadodara',          'Pune', 'Visakhapatnam',        'Jaipur',
      'Bareilly',        'Kanpur',      'Ludhiana',        'Meerut',
    'Saharanpur',        'Nagpur',         'Surat',    'Chandigarh',
     'Gorakhpur',         'Kochi',      'Varanasi',     'Allahabad',
     'Moradabad',       'Aligarh']
Length: 30, dtype: str

In [19]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2020[col] = year_2020[col].map(bool_map)

In [20]:
year_2020[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0             True              False             False
1            False               True             False
2            False               True             False
3             True               True              True
4            False              False             False

In [21]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2020['category'] = (
    year_2020['category']
    .replace(category_map)
)

In [22]:
year_2020['category'].value_counts()

category
Electronics    143715
Name: count, dtype: int64

In [23]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2020['delivery_days'] = year_2020['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2020['delivery_days'] = pd.to_numeric(
    year_2020['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2020.loc[
    (year_2020['delivery_days'] >= 0) &
    (year_2020['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2020.loc[
    (year_2020['delivery_days'] < 0) |
    (year_2020['delivery_days'] > 30) |
    (year_2020['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2020['delivery_days'] = year_2020['delivery_days'].astype(int)

In [24]:
year_2020['delivery_days'].value_counts()

delivery_days
3     37901
4     26808
1     26287
5     17712
2     16044
6     13317
7      4479
0       880
15      287
Name: count, dtype: int64

In [26]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2020.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2020 = year_2020.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2020.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 715
Duplicates after removal: 0

In [27]:
year_2020['original_price_inr'].describe()

count    1.430000e+05
mean     9.919610e+04
std      4.674405e+05
min     -2.853604e+05
25%      3.621176e+04
50%      5.404659e+04
75%      1.173206e+05
max      2.790274e+07
Name: original_price_inr, dtype: float64

In [28]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [29]:
#Q9 - column to contain the base price of the product in 2020.
year_2020 = year_2020.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2020['price_ratio'] = year_2020['original_price_inr'] / year_2020['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2020['price_ratio'] < 0.3) | (year_2020['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2020.loc[mask, 'original_price_inr'] = year_2020['base_price_2015'] # Replace outliers with base price
year_2020.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [30]:
year_2020['original_price_inr'].describe()

count    143000.000000
mean      79650.802665
std       58654.817737
min        1153.580000
25%       36211.760000
50%       54043.530000
75%      116326.370000
max      326570.000000
Name: original_price_inr, dtype: float64

In [31]:
year_2020['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [32]:
year_2020.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        17160
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             99399
customer_rating           43412
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [33]:
year_2020['customer_rating'].unique()

array([4.5, nan, 5. , 4. , 3.5, 3. ])

In [34]:
year_2020['customer_rating'] = (year_2020['customer_rating'].replace(1, np.nan))

In [35]:
year_2020['festival_name'] = (year_2020['festival_name'].fillna('Regular Sale'))

In [41]:
year_2020['customer_age_group'] = year_2020['customer_age_group'].fillna('Unknown')
year_2020 = year_2020.dropna(subset=['customer_rating'])

In [42]:
year_2020.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [43]:
year_2020.to_csv(
    '2020_cleaned.csv',
    index=False
)

In [44]:
year_2020

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2020_00000001,2020-01-19,CUST_2020_00001031,PROD_000402,Xiaomi Poco F1 128GB Blue,Electronics,Smartphones,Xiaomi,36202.67,7.11,...,False,Regular Sale,4.5,Cancelled,1,2020,1,0.19,False,3.4
2,TXN_2020_00000003,2020-01-17,CUST_2020_00001673,PROD_000278,Xiaomi Redmi 4A 16GB White,Electronics,Smartphones,Xiaomi,32906.94,0.00,...,False,Regular Sale,5.0,Delivered,1,2020,1,0.21,True,4.1
3,TXN_2020_00000004,2020-01-25,CUST_2020_00026212,PROD_000245,Samsung Galaxy S8+ 32GB Black,Electronics,Smartphones,Samsung,136675.37,45.87,...,True,Republic Day Sale,4.5,Delivered,1,2020,1,0.23,True,3.8
4,TXN_2020_00000005,2020-01-01,CUST_2015_00009980,PROD_000765,Vivo V20 64GB Black,Electronics,Smartphones,Vivo,30041.81,0.00,...,False,Regular Sale,4.0,Delivered,1,2020,1,0.23,False,3.9
6,TXN_2020_00000007,2020-01-18,CUST_2020_00005890,PROD_000396,OnePlus OnePlus 6T 128GB Blue,Electronics,Smartphones,OnePlus,57597.55,0.00,...,False,Regular Sale,3.5,Delivered,1,2020,1,0.21,True,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142993,TXN_2020_00142994,2020-12-20,CUST_2018_00004441,PROD_000581,Realme Realme 3 64GB White,Electronics,Smartphones,Realme,53640.12,0.00,...,False,Regular Sale,4.0,Delivered,12,2020,4,0.17,False,3.4
142995,TXN_2020_00142996,2020-12-09,CUST_2020_00046734,PROD_000756,Realme Realme Narzo 10 256GB White,Electronics,Smartphones,Realme,45866.68,0.00,...,False,Regular Sale,5.0,Delivered,12,2020,4,0.22,False,4.4
142996,TXN_2020_00142997,2020-12-02,CUST_2015_00007531,PROD_000407,Xiaomi Redmi 5A 256GB Black,Electronics,Smartphones,Xiaomi,54445.98,0.00,...,False,Regular Sale,4.0,Delivered,12,2020,4,0.23,True,4.6
142997,TXN_2020_00142998,2020-12-30,CUST_2019_00001469,PROD_000579,Realme Realme 3 128GB Black,Electronics,Smartphones,Realme,34791.59,0.00,...,False,Regular Sale,4.5,Delivered,12,2020,4,0.21,False,4.5
142998,TXN_2020_00142999,2020-12-15,CUST_2020_00013205,PROD_000768,Vivo V20 128GB White,Electronics,Smartphones,Vivo,44156.98,0.00,...,False,Regular Sale,4.5,Delivered,12,2020,4,0.22,True,4.3