In [2]:
import pandas as pd
import numpy as np

In [3]:
year_2021 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2021.csv")
year_2021

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2021_00000001,2021-01-29,CUST_2021_00014071,PROD_000178,Xiaomi Mi 5 64GB Black,Electronics,Smartphones,Xiaomi,43292.78,22.96,...,False,NaN,4.5,Delivered,1,2021,1,0.24,True,3.7
1,TXN_2021_00000002,2021-01-10,CUST_2019_00006495,PROD_000610,Vivo V15 Pro 256GB White,Electronics,Smartphones,Vivo,32964.72,16.68,...,False,NaN,5.0,Delivered,1,2021,1,0.19,True,4.1
2,TXN_2021_00000003,2021-01-18,CUST_2018_00029239,PROD_000404,Xiaomi Poco F1 128GB Gold,Electronics,Smartphones,Xiaomi,45794.75,0.00,...,False,NaN,NaN,Delivered,1,2021,1,0.22,True,4.4
3,TXN_2021_00000004,2021-01-08,CUST_2021_00040991,PROD_000664,Apple iPhone SE (2nd gen) 64GB Gold,Electronics,Smartphones,Apple,136337.08,0.00,...,False,NaN,4.0,Delivered,1,2021,1,0.17,True,3.8
4,TXN_2021_00000005,2021-01-02,CUST_2016_00006478,PROD_000466,Oppo A3s 64GB Black,Electronics,Smartphones,Oppo,19992.12,0.00,...,False,NaN,3.0,Delivered,1,2021,1,0.24,1,3.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138182,TXN_2021_00135877_DUP,12/24/2021,CUST_2016_00000089,PROD_000402,Xiaomi Poco F1 128GB Blue,Electronics,Smartphones,Xiaomi,34242.15,23.22,...,False,NaN,5.0,Delivered,12,2021,4,0.19,False,3.4
138183,TXN_2021_00065427_DUP,2021-07-15,CUST_2017_00004814,PROD_001904,Xiaomi Tracker Premium,Electronics,Smart Watch,Xiaomi,"Rs 60,140",15.86,...,True,Prime Day,NaN,Delivered,7,2021,3,0.06,False,4.1
138184,TXN_2021_00012199_DUP,2021-02-01,CUST_2021_00012902,PROD_000904,Realme Realme Narzo 30 64GB Blue,Electronics,Smartphones,Realme,46453.23,28.15,...,0,NaN,4.0,Delivered,2,2021,1,0.19,False,3.8
138185,TXN_2021_00118907_DUP,2021-11-16,CUST_2021_00016509,PROD_001558,Lenovo VivoBook 4GB RAM Black,Electronics,Laptops,Lenovo,51021.72,0.00,...,False,NaN,3.0,Delivered,11,2021,4,2.76,True,4.0
138186,TXN_2021_00065789_DUP,2021-07-27,CUST_2021_00039165,PROD_000599,Vivo V15 64GB Black,Electronics,Smartphones,Vivo,"33,321.1",0.00,...,False,NaN,4.5,Delivered,7,2021,3,0.19,True,4.1

In [4]:
year_2021.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges          11040
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        16585
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             95887
customer_rating           41885
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [5]:
year_2021['delivery_charges'] = year_2021['delivery_charges'].fillna(0.0)

In [6]:
year_2021.duplicated().sum()

np.int64(0)

In [7]:
year_2021['order_date'].isna().sum()

np.int64(0)

In [8]:
#Q1 datetime format 

year_2021['order_date'] = pd.to_datetime(
    year_2021['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2021['order_date'].dropna().median()

year_2021['order_date'] = (
    year_2021['order_date']
    .fillna(median_date)
)

# Standardize format
year_2021['order_date'] = (
    year_2021['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [9]:
year_2021['order_date'].iloc[15:50]

15    2021-01-25
16    2021-01-23
17    2021-01-26
18    2021-01-21
19    2021-01-16
20    2021-09-01
21    2021-01-28
22    2021-01-27
23    2021-01-24
24    2021-01-22
25    2021-01-15
26    2021-01-27
27    2021-01-29
28    2021-01-24
29    2021-01-22
30    2021-03-01
31    2021-01-29
32    2021-01-28
33    2021-08-01
34    2021-04-01
35    2021-09-01
36    2021-12-01
37    2021-01-25
38    2021-01-18
39    2021-01-25
40    2021-06-01
41    2021-05-01
42    2021-02-01
43    2021-12-01
44    2021-11-01
45    2021-01-23
46    2021-09-01
47    2021-01-13
48    2021-01-23
49    2021-01-16
Name: order_date, dtype: str

In [10]:
year_2021['original_price_inr'].iloc[16:45]

16      22441.34
17     106984.36
18      39094.74
19      41661.86
20     104823.81
21      97710.86
22      29063.13
23     101494.71
24      95567.85
25       34933.6
26      70922.06
27      172668.2
28      187651.6
29      52593.72
30     119308.57
31      33822.84
32      49338.01
33     166980.78
34      45676.86
35       29366.2
36       50974.2
37      46820.15
38    ₹38,490.78
39       64356.3
40      25982.42
41       34012.7
42      25837.37
43      29063.13
44     193784.34
Name: original_price_inr, dtype: str

In [11]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2021['original_price_inr'] = year_2021['original_price_inr'].str.replace('₹', '', regex=False)
year_2021['original_price_inr'] = year_2021['original_price_inr'].str.replace('Rs', '', regex=False)
year_2021['original_price_inr'] = year_2021['original_price_inr'].str.replace(',', '', regex=False)
year_2021['original_price_inr'] = year_2021['original_price_inr'].astype(float)

year_2021['original_price_inr'].iloc[16:45]

16     22441.34
17    106984.36
18     39094.74
19     41661.86
20    104823.81
21     97710.86
22     29063.13
23    101494.71
24     95567.85
25     34933.60
26     70922.06
27    172668.20
28    187651.60
29     52593.72
30    119308.57
31     33822.84
32     49338.01
33    166980.78
34     45676.86
35     29366.20
36     50974.20
37     46820.15
38     38490.78
39     64356.30
40     25982.42
41     34012.70
42     25837.37
43     29063.13
44    193784.34
Name: original_price_inr, dtype: float64

In [12]:
year_2021['original_price_inr']

0          43292.78
1          32964.72
2          45794.75
3         136337.08
4          19992.12
            ...
138182     34242.15
138183     60140.00
138184     46453.23
138185     51021.72
138186     33321.10
Name: original_price_inr, Length: 138187, dtype: float64

In [13]:
year_2021['customer_rating'].value_counts()

customer_rating
4.5          30090
5.0          22790
4.0          21381
3.5           9290
3.0           5044
4/5           1374
4.5 stars     1020
4.0 stars      751
5.0 stars      747
5/5            626
4.5/5.0        493
4              492
5.0/5.0        387
3/5            385
4.0/5.0        354
3.5 stars      335
5              174
3.5/5.0        172
3.0 stars      165
3              143
3.0/5.0         89
Name: count, dtype: int64

In [14]:
#Q3 - column to contain only numeric values representing the rating.
year_2021['customer_rating'] = year_2021['customer_rating'].astype(str) # Convert to string for processing
year_2021['customer_rating'] = year_2021['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2021['customer_rating'] = year_2021['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2021['customer_rating'] = year_2021['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2021['customer_rating'] = pd.to_numeric(year_2021['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [15]:
year_2021['customer_rating'].value_counts()

customer_rating
4.5    31603
5.0    24724
4.0    24352
3.5     9797
3.0     5826
Name: count, dtype: int64

In [16]:
year_2021['customer_city'].unique()

<StringArray>
[       'Mumbai',        'Jaipur',      'Bareilly',         'Surat',
      'Vadodara',       'Kolkata',     'Bangalore',    'Saharanpur',
    'Coimbatore',        'Kanpur',       'Chennai',          'Pune',
       'Lucknow',        'Indore',         'Delhi',     'Ahmedabad',
         'Kochi',     'Allahabad',    'Chandigarh',   'Bhubaneswar',
 'Visakhapatnam',      'Ludhiana',        'Nagpur',         'Patna',
     'Hyderabad',       'Aligarh',      'Varanasi',        'Meerut',
        'Madras',     'Gorakhpur',      'Calcutta',     'Moradabad',
         'mumba',        'Bombay',         'DELHI',        'chenai',
     'BANGALORE',       'Mumbai ',      'Chennai ',     'Bengaluru',
      'Banglore',       'kolkata',     'Bengalore',       'KOLKATA',
     'Delhi NCR',         'delhi',      'Kolkata ',     'New Delhi',
        'MUMBAI',       'CHENNAI']
Length: 50, dtype: str

In [18]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2021['customer_city'] = year_2021['customer_city'].replace(city_map)

year_2021['customer_city'] = year_2021['customer_city'].str.title()
year_2021['customer_city'].unique()

<StringArray>
[       'Mumbai',        'Jaipur',      'Bareilly',         'Surat',
      'Vadodara',       'Kolkata',     'Bengaluru',    'Saharanpur',
    'Coimbatore',        'Kanpur',       'Chennai',          'Pune',
       'Lucknow',        'Indore',         'Delhi',     'Ahmedabad',
         'Kochi',     'Allahabad',    'Chandigarh',   'Bhubaneswar',
 'Visakhapatnam',      'Ludhiana',        'Nagpur',         'Patna',
     'Hyderabad',       'Aligarh',      'Varanasi',        'Meerut',
     'Gorakhpur',     'Moradabad']
Length: 30, dtype: str

In [19]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2021[col] = year_2021[col].map(bool_map)

In [20]:
year_2021[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0             True               True             False
1            False               True             False
2            False               True             False
3             True               True             False
4            False               True             False

In [26]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2021['category'] = (
    year_2021['category']
    .replace(category_map)
)

In [22]:
year_2021['category'].value_counts()

category
Electronics    138187
Name: count, dtype: int64

In [23]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2021['delivery_days'] = year_2021['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2021['delivery_days'] = pd.to_numeric(
    year_2021['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2021.loc[
    (year_2021['delivery_days'] >= 0) &
    (year_2021['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2021.loc[
    (year_2021['delivery_days'] < 0) |
    (year_2021['delivery_days'] > 30) |
    (year_2021['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2021['delivery_days'] = year_2021['delivery_days'].astype(int)

In [24]:
year_2021['delivery_days'].value_counts()

delivery_days
3     35149
1     30620
4     22740
2     18654
5     15112
6     11172
7      3668
0       813
15      259
Name: count, dtype: int64

In [25]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2021.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2021 = year_2021.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2021.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 687
Duplicates after removal: 0

In [27]:
year_2021['original_price_inr'].describe()

count    1.375000e+05
mean     9.408597e+04
std      4.183457e+05
min     -2.750701e+05
25%      3.456003e+04
50%      5.110506e+04
75%      1.097155e+05
max      2.751160e+07
Name: original_price_inr, dtype: float64

In [28]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [29]:
#Q9 - column to contain the base price of the product in 2021.
year_2021 = year_2021.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2021['price_ratio'] = year_2021['original_price_inr'] / year_2021['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2021['price_ratio'] < 0.3) | (year_2021['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2021.loc[mask, 'original_price_inr'] = year_2021['base_price_2015'] # Replace outliers with base price
year_2021.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [30]:
year_2021['original_price_inr'].describe()

count    137500.000000
mean      76782.571834
std       59675.210256
min        1284.980000
25%       34560.000000
50%       51021.720000
75%      108302.490000
max      420705.000000
Name: original_price_inr, dtype: float64

In [31]:
year_2021['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [32]:
year_2021.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        16500
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             95416
customer_rating           41667
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [33]:
year_2021['customer_rating'].unique()

array([4.5, 5. , nan, 4. , 3. , 3.5])

In [34]:
year_2021['customer_rating'] = (year_2021['customer_rating'].replace(1, np.nan))

In [35]:
year_2021['festival_name'] = (year_2021['festival_name'].fillna('Regular Sale'))

In [39]:
year_2021['customer_age_group'] = year_2021['customer_age_group'].fillna('Unknown')
year_2021 = year_2021.dropna(subset=['customer_rating'])

In [40]:
year_2021.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [41]:
year_2021.to_csv(
    '2021_cleaned.csv',
    index=False
)

In [37]:
year_2021.iloc[16:30]

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
16,TXN_2021_00000017,2021-01-23,CUST_2021_00002624,PROD_000899,Realme Realme GT 128GB Blue,Electronics,Smartphones,Realme,22441.34,46.82,...,True,Republic Day Sale,3.5,Returned,1,2021,1,0.20,True,4.3
17,TXN_2021_00000018,2021-01-26,CUST_2021_00036777,PROD_000164,OnePlus OnePlus 3T 32GB Black,Electronics,Smartphones,OnePlus,106984.36,15.94,...,True,Republic Day Sale,NaN,Returned,1,2021,1,0.18,True,4.2
18,TXN_2021_00000019,2021-01-21,CUST_2021_00013704,PROD_000309,Vivo Y69 32GB White,Electronics,Smartphones,Vivo,39094.74,68.04,...,True,Republic Day Sale,5.0,Delivered,1,2021,1,0.18,True,4.0
19,TXN_2021_00000020,2021-01-16,CUST_2021_00027134,PROD_000181,Xiaomi Mi 5 64GB White,Electronics,Smartphones,Xiaomi,41661.86,23.40,...,False,Regular Sale,4.5,Delivered,1,2021,1,0.21,True,4.2
20,TXN_2021_00000021,2021-09-01,CUST_2021_00036479,PROD_001749,Realme Pad 4GB RAM Silver,Electronics,Tablets,Realme,104823.81,0.00,...,False,Regular Sale,4.5,Delivered,1,2021,1,0.52,True,3.0
21,TXN_2021_00000022,2021-01-28,CUST_2021_00007487,PROD_000029,Samsung Galaxy S6 Edge 16GB Black,Electronics,Smartphones,Samsung,97710.86,18.95,...,False,Regular Sale,4.5,Returned,1,2021,1,0.17,True,3.8
22,TXN_2021_00000023,2021-01-27,CUST_2018_00002096,PROD_000197,Motorola Moto G4 32GB Gold,Electronics,Smartphones,Motorola,29063.13,0.00,...,False,Regular Sale,4.5,Returned,1,2021,1,0.20,True,4.1
23,TXN_2021_00000024,2021-01-24,CUST_2020_00016285,PROD_000161,OnePlus OnePlus 3 16GB Blue,Electronics,Smartphones,OnePlus,101494.71,20.62,...,True,Republic Day Sale,NaN,Delivered,1,2021,1,0.20,True,4.3
24,TXN_2021_00000025,2021-01-22,CUST_2018_00021333,PROD_000709,OnePlus OnePlus 8 Pro 256GB White,Electronics,Smartphones,OnePlus,95567.85,29.42,...,True,Republic Day Sale,NaN,Delivered,1,2021,1,0.25,True,4.1
25,TXN_2021_00000026,2021-01-15,CUST_2021_00045411,PROD_000432,Realme Realme C1 64GB Black,Electronics,Smartphones,Realme,34933.60,14.57,...,False,Regular Sale,4.0,Delivered,1,2021,1,0.25,True,4.6
26,TXN_2021_00000027,2021-01-27,CUST_2021_00041239,PROD_001899,Xiaomi Watch Premium,Electronics,Smart Watch,Xiaomi,70922.06,8.06,...,False,Regular Sale,4.5,Returned,1,2021,1,0.06,True,4.2
27,TXN_2021_00000028,2021-01-29,CUST_2021_00029783,PROD_000366,Samsung Galaxy S9+ 64GB White,Electronics,Smartphones,Samsung,172668.20,11.00,...,False,Regular Sale,5.0,Delivered,1,2021,1,0.21,True,4.0
28,TXN_2021_00000029,2021-01-24,CUST_2021_00016289,PROD_000491,Apple iPhone 11 Pro 64GB White,Electronics,Smartphones,Apple,187651.60,23.61,...,True,Republic Day Sale,5.0,Delivered,1,2021,1,0.23,False,4.7
29,TXN_2021_00000030,2021-01-22,CUST_2021_00025000,PROD_000046,Samsung Galaxy J7 32GB Black,Electronics,Smartphones,Samsung,52593.72,28.46,...,True,Republic Day Sale,3.0,Delivered,1,2021,1,0.24,False,3.8