In [3]:
import pandas as pd
import numpy as np

In [4]:
year_2022 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2022.csv")
year_2022

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2022_00000001,2022-01-22,CUST_2022_00015913,PROD_000527,Samsung Galaxy A50 64GB White,Electronics,Smartphones,Samsung,26992.07,41.06,...,True,Republic Day Sale,4.0,Delivered,1,2022,1,0.20,0,4.2
1,TXN_2022_00000002,2022-01-11,CUST_2022_00021843,PROD_000979,Samsung Galaxy S22+ 128GB White,Electronics,Smartphones,Samsung,80105.77,0.00,...,False,NaN,NaN,Delivered,1,2022,1,0.24,False,3.3
2,TXN_2022_00000003,17-01-2022,CUST_2019_00043917,PROD_001909,Xiaomi Fitness Band Deluxe,Electronics,Smart Watch,Xiaomi,27516.92,0.00,...,False,NaN,4.0,Delivered,1,2022,1,0.05,True,4.2
3,TXN_2022_00000004,2022-01-27,CUST_2022_00011696,PROD_000284,Xiaomi Mi A1 32GB White,Electronics,Smartphones,Xiaomi,38018.11,0.00,...,FALSE,NaN,4.0,Delivered,1,2022,1,0.24,True,4.6
4,TXN_2022_00000005,2022-01-16,CUST_2022_00030756,PROD_000556,OnePlus OnePlus 7T 64GB Gold,Electronics,Smartphones,OnePlus,87743.24,0.00,...,False,NaN,NaN,Delivered,1,2022,1,0.18,True,3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132655,TXN_2022_00027248_DUP,2022-03-16,CUST_2022_00011638,PROD_000972,Samsung Galaxy S22 128GB White,Electronics,Smartphones,Samsung,"₹75,294.24",7.30,...,False,NaN,NaN,Delivered,3,2022,1,0.23,True,4.2
132656,TXN_2022_00010369_DUP,2022-01-27,CUST_2022_00036128,PROD_001568,ASUS ThinkPad 4GB RAM Silver,Electronics,Laptops,ASUS,76375.15,20.34,...,False,NaN,5.0,Delivered,1,2022,1,2.69,True,4.5
132657,TXN_2022_00053894_DUP,19-06-2022,CUST_2022_00001209,PROD_001945,Garmin Fitness Band,Electronics,Smart Watch,Garmin,42642.37,62.52,...,True,Back to School,5.0,Delivered,6,2022,2,0.05,False,3.3
132658,TXN_2022_00051412_DUP,22-06-2022,CUST_2016_00009941,PROD_000529,Samsung Galaxy A50 64GB Blue,Electronics,Smartphones,Samsung,17093.64,38.66,...,True,Back to School,4.0,Delivered,6,2022,2,0.18,True,3.7
132659,TXN_2022_00037100_DUP,2022-04-25,CUST_2020_00002532,PROD_000053,OnePlus OnePlus 2 32GB Black,Electronics,Smartphones,OnePlus,92885.64,0.00,...,False,NaN,5.0,Delivered,4,2022,2,0.20,True,4.6

In [5]:
year_2022.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges          10616
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        15917
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             91868
customer_rating           40206
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [6]:
year_2022['delivery_charges'] = year_2022['delivery_charges'].fillna(0.0)

In [7]:
year_2022.duplicated().sum()

np.int64(0)

In [8]:
year_2022['order_date'].isna().sum()

np.int64(0)

In [9]:
#Q1 datetime format 

year_2022['order_date'] = pd.to_datetime(
    year_2022['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2022['order_date'].dropna().median()

year_2022['order_date'] = (
    year_2022['order_date']
    .fillna(median_date)
)

# Standardize format
year_2022['order_date'] = (
    year_2022['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [10]:
year_2022['order_date'].iloc[15:50]

15    2022-03-01
16    2022-01-22
17    2022-12-01
18    2022-01-22
19    2022-12-01
20    2022-01-29
21    2022-02-01
22    2022-01-20
23    2022-11-01
24    2022-01-25
25    2022-01-15
26    2022-01-01
27    2022-01-18
28    2022-01-28
29    2022-01-20
30    2022-01-17
31    2022-01-15
32    2022-04-01
33    2022-01-21
34    2022-01-14
35    2022-01-23
36    2022-01-27
37    2022-04-01
38    2022-01-30
39    2022-01-15
40    2022-10-01
41    2022-08-01
42    2022-01-26
43    2022-01-11
44    2022-12-01
45    2022-06-01
46    2022-01-25
47    2022-01-15
48    2022-01-22
49    2022-01-28
Name: order_date, dtype: str

In [11]:
year_2022['original_price_inr'].iloc[16:45]

16      36182.34
17      28244.07
18    Rs 300,375
19     116292.79
20     100726.74
21     130172.15
22      94548.64
23     144163.34
24      43974.88
25      33881.13
26       42118.2
27      96118.38
28      22561.54
29      41285.19
30     117698.49
31      47284.22
32      20265.21
33      40369.69
34      49994.19
35      31093.47
36      39998.73
37     218988.47
38     Rs 37,642
39      32375.56
40     123917.39
41      38581.99
42      84401.17
43       69990.7
44       78421.1
Name: original_price_inr, dtype: str

In [12]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2022['original_price_inr'] = year_2022['original_price_inr'].str.replace('₹', '', regex=False)
year_2022['original_price_inr'] = year_2022['original_price_inr'].str.replace('Rs', '', regex=False)
year_2022['original_price_inr'] = year_2022['original_price_inr'].str.replace(',', '', regex=False)
year_2022['original_price_inr'] = year_2022['original_price_inr'].astype(float)

year_2022['original_price_inr'].iloc[16:45]

16     36182.34
17     28244.07
18    300375.00
19    116292.79
20    100726.74
21    130172.15
22     94548.64
23    144163.34
24     43974.88
25     33881.13
26     42118.20
27     96118.38
28     22561.54
29     41285.19
30    117698.49
31     47284.22
32     20265.21
33     40369.69
34     49994.19
35     31093.47
36     39998.73
37    218988.47
38     37642.00
39     32375.56
40    123917.39
41     38581.99
42     84401.17
43     69990.70
44     78421.10
Name: original_price_inr, dtype: float64

In [13]:
year_2022['original_price_inr']

0         26992.07
1         80105.77
2         27516.92
3         38018.11
4         87743.24
            ...
132655    75294.24
132656    76375.15
132657    42642.37
132658    17093.64
132659    92885.64
Name: original_price_inr, Length: 132660, dtype: float64

In [14]:
year_2022['customer_rating'].value_counts()

customer_rating
4.5          28754
5.0          21437
4.0          20905
3.5           9089
3.0           4878
4/5           1249
4.5 stars     1033
5.0 stars      785
4.0 stars      704
5/5            585
4.5/5.0        501
4              402
5.0/5.0        386
3/5            379
4.0/5.0        363
3.5 stars      304
3.0 stars      163
5              161
3.5/5.0        160
3              130
3.0/5.0         86
Name: count, dtype: int64

In [15]:
#Q3 - column to contain only numeric values representing the rating.
year_2022['customer_rating'] = year_2022['customer_rating'].astype(str) # Convert to string for processing
year_2022['customer_rating'] = year_2022['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2022['customer_rating'] = year_2022['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2022['customer_rating'] = year_2022['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2022['customer_rating'] = pd.to_numeric(year_2022['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [16]:
year_2022['customer_rating'].value_counts()

customer_rating
4.5    30288
4.0    23623
5.0    23354
3.5     9553
3.0     5636
Name: count, dtype: int64

In [17]:
year_2022['customer_city'].unique()

<StringArray>
[     'Vadodara',       'Chennai',         'Delhi',     'Gorakhpur',
      'Ludhiana',          'Pune',       'Lucknow',        'Kanpur',
        'Indore',     'Ahmedabad',       'Kolkata',        'Mumbai',
     'Bangalore',    'Coimbatore',        'Nagpur',     'Moradabad',
        'Jaipur', 'Visakhapatnam',    'Saharanpur',         'Patna',
    'Chandigarh',     'Allahabad',   'Bhubaneswar',         'Kochi',
     'Hyderabad',       'Aligarh',         'Surat',      'Bareilly',
     'New Delhi',         'delhi',      'Varanasi',        'Meerut',
      'Chennai ',       'Mumbai ',        'MUMBAI',     'BANGALORE',
        'chenai',      'Calcutta',        'Bombay',     'Delhi NCR',
       'kolkata',         'mumba',        'Madras',     'Bengalore',
         'DELHI',      'Banglore',     'Bengaluru',       'KOLKATA',
       'CHENNAI',      'Kolkata ']
Length: 50, dtype: str

In [38]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2022['customer_city'] = year_2022['customer_city'].replace(city_map)

year_2022['customer_city'] = year_2022['customer_city'].str.title()
year_2022['customer_city'].unique()

<StringArray>
[     'Vadodara',       'Chennai',         'Delhi',     'Gorakhpur',
      'Ludhiana',          'Pune',       'Lucknow',        'Kanpur',
        'Indore',     'Ahmedabad',       'Kolkata',        'Mumbai',
     'Bengaluru',    'Coimbatore',        'Nagpur',     'Moradabad',
        'Jaipur', 'Visakhapatnam',    'Saharanpur',         'Patna',
    'Chandigarh',     'Allahabad',   'Bhubaneswar',         'Kochi',
     'Hyderabad',       'Aligarh',         'Surat',      'Bareilly',
      'Varanasi',        'Meerut']
Length: 30, dtype: str

In [19]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2022[col] = year_2022[col].map(bool_map)

In [20]:
year_2022[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0             True              False              True
1             True              False             False
2             True               True             False
3             True               True             False
4             True               True             False

In [21]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2022['category'] = (
    year_2022['category']
    .replace(category_map)
)

In [22]:
year_2022['category'].value_counts()

category
Electronics    132660
Name: count, dtype: int64

In [23]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2022['delivery_days'] = year_2022['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2022['delivery_days'] = pd.to_numeric(
    year_2022['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2022.loc[
    (year_2022['delivery_days'] >= 0) &
    (year_2022['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2022.loc[
    (year_2022['delivery_days'] < 0) |
    (year_2022['delivery_days'] > 30) |
    (year_2022['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2022['delivery_days'] = year_2022['delivery_days'].astype(int)

In [24]:
year_2022['delivery_days'].value_counts()

delivery_days
1     33486
3     33177
2     20563
4     18941
5     12697
6      9583
7      3163
0       808
15      242
Name: count, dtype: int64

In [25]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2022.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2022 = year_2022.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2022.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 660
Duplicates after removal: 0

In [26]:
year_2022['original_price_inr'].describe()

count    1.320000e+05
mean     7.913277e+04
std      4.202817e+05
min     -2.165010e+05
25%      2.761935e+04
50%      4.105539e+04
75%      8.744426e+04
max      3.337169e+07
Name: original_price_inr, dtype: float64

In [27]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [28]:
#Q9 - column to contain the base price of the product in 2022.
year_2022 = year_2022.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2022['price_ratio'] = year_2022['original_price_inr'] / year_2022['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2022['price_ratio'] < 0.3) | (year_2022['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2022.loc[mask, 'original_price_inr'] = year_2022['base_price_2015'] # Replace outliers with base price
year_2022.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [29]:
year_2022['original_price_inr'].describe()

count    132000.000000
mean      62189.508565
std       48934.275799
min        1075.320000
25%       27640.390000
50%       40566.070000
75%       86740.460000
max      333717.000000
Name: original_price_inr, dtype: float64

In [30]:
year_2022['festival_name'].unique()

<StringArray>
[           'Republic Day Sale',                            nan,
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [31]:
year_2022.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        15840
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             91399
customer_rating           40029
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [32]:
year_2022['customer_rating'].unique()

array([4. , nan, 4.5, 5. , 3.5, 3. ])

In [33]:
year_2022['customer_rating'] = (year_2022['customer_rating'].replace(1, np.nan))

In [34]:
year_2022['festival_name'] = (year_2022['festival_name'].fillna('Regular Sale'))

In [40]:
year_2022['customer_age_group'] = year_2022['customer_age_group'].fillna('Unknown')
year_2022 = year_2022.dropna(subset=['customer_rating'])

In [41]:
year_2022.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [42]:
year_2022.to_csv(
    '2022_cleaned.csv',
    index=False
)

In [37]:
year_2022.iloc[16:30]

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
16,TXN_2022_00000017,2022-01-22,CUST_2020_00048503,PROD_000441,Vivo V11 128GB Black,Electronics,Smartphones,Vivo,36182.34,60.39,...,True,Republic Day Sale,4.5,Delivered,1,2022,1,0.23,True,4.4
17,TXN_2022_00000018,2022-12-01,CUST_2021_00049828,PROD_000634,Oppo Reno 128GB White,Electronics,Smartphones,Oppo,28244.07,0.00,...,False,Regular Sale,NaN,Delivered,1,2022,1,0.25,True,3.6
18,TXN_2022_00000019,2022-01-22,CUST_2017_00024869,PROD_000950,Apple iPhone 14 256GB White,Electronics,Smartphones,Apple,300375.00,29.49,...,True,Republic Day Sale,4.0,Delivered,1,2022,1,0.23,True,3.9
19,TXN_2022_00000020,2022-12-01,CUST_2018_00024826,PROD_000230,Apple iPhone X 16GB Black,Electronics,Smartphones,Apple,116292.79,6.02,...,False,Regular Sale,5.0,Delivered,1,2022,1,0.25,True,3.2
20,TXN_2022_00000021,2022-01-29,CUST_2019_00017551,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,100726.74,0.00,...,False,Regular Sale,3.5,Delivered,1,2022,1,0.17,True,3.3
21,TXN_2022_00000022,2022-02-01,CUST_2022_00045286,PROD_000220,Apple iPhone 8 16GB Blue,Electronics,Smartphones,Apple,130172.15,0.00,...,False,Regular Sale,5.0,Delivered,1,2022,1,0.24,True,4.5
22,TXN_2022_00000023,2022-01-20,CUST_2022_00017165,PROD_000682,Samsung Galaxy Note 20 128GB Black,Electronics,Smartphones,Samsung,94548.64,56.66,...,True,Republic Day Sale,3.5,Delivered,1,2022,1,0.21,True,3.6
23,TXN_2022_00000024,2022-11-01,CUST_2022_00003176,PROD_000023,Samsung Galaxy S6 64GB Black,Electronics,Smartphones,Samsung,144163.34,0.00,...,False,Regular Sale,5.0,Delivered,1,2022,1,0.16,True,3.9
24,TXN_2022_00000025,2022-01-25,CUST_2022_00014496,PROD_001721,Xiaomi Galaxy Tab 4GB RAM Black,Electronics,Tablets,Xiaomi,43974.88,66.44,...,True,Republic Day Sale,3.0,Delivered,1,2022,1,0.43,False,3.3
25,TXN_2022_00000026,2022-01-15,CUST_2020_00013892,PROD_000276,Xiaomi Redmi 4A 32GB Black,Electronics,Smartphones,Xiaomi,33881.13,0.00,...,False,Regular Sale,4.5,Delivered,1,2022,1,0.22,True,3.9
26,TXN_2022_00000027,2022-01-01,CUST_2018_00032680,PROD_001626,MSI ThinkPad 4GB RAM Silver,Electronics,Laptops,MSI,42118.20,27.09,...,False,Regular Sale,4.5,Delivered,1,2022,1,2.31,False,4.0
27,TXN_2022_00000028,2022-01-18,CUST_2022_00038207,PROD_000835,Samsung Galaxy Note 21 64GB Black,Electronics,Smartphones,Samsung,96118.38,13.41,...,False,Regular Sale,4.5,Delivered,1,2022,1,0.16,True,4.5
28,TXN_2022_00000029,2022-01-28,CUST_2022_00028956,PROD_000930,Oppo F19 64GB White,Electronics,Smartphones,Oppo,22561.54,28.45,...,False,Regular Sale,4.0,Delivered,1,2022,1,0.22,True,3.5
29,TXN_2022_00000030,2022-01-20,CUST_2021_00022013,PROD_000155,OnePlus OnePlus 3 16GB Black,Electronics,Smartphones,OnePlus,41285.19,17.68,...,True,Republic Day Sale,5.0,Delivered,1,2022,1,0.23,True,3.3