In [4]:
import pandas as pd
import numpy as np

In [5]:
year_2023 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2023.csv")
year_2023

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2023_00000001,2023-01-16,CUST_2023_00005822,PROD_001899,Xiaomi Watch Premium,Electronics,Smart Watch,Xiaomi,59416.51,0.00,...,False,NaN,4/5,Returned,1,2023,1,0.06,True,4.2
1,TXN_2023_00000002,2023-01-15,CUST_2019_00019403,PROD_000472,Oppo R17 Pro 64GB Black,Electronics,Smartphones,Oppo,19474.76,0.00,...,False,NaN,4.0,Returned,1,2023,1,0.16,True,3.4
2,TXN_2023_00000003,2023-01-10,CUST_2023_00040022,PROD_001759,JBL Neckband,Electronics,Audio,JBL,27097.23,27.71,...,False,NaN,5.0,Delivered,1,2023,1,0.23,True,3.7
3,TXN_2023_00000004,2023-01-04,CUST_2023_00021818,PROD_001158,Xiaomi Redmi Note 12 256GB White,Electronics,Smartphones,Xiaomi,12883.85,0.00,...,False,NaN,3.5,Delivered,1,2023,1,0.23,True,4.1
4,TXN_2023_00000005,2023-01-07,CUST_2020_00048935,PROD_000221,Apple iPhone 8 32GB Blue,Electronics,Smartphones,Apple,165637.56,0.00,...,False,NaN,3.0,Delivered,1,2023,1,0.22,False,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127127,TXN_2023_00010663_DUP,2023-02-10,CUST_2021_00032315,PROD_001683,Apple Mi Pad 8GB RAM Silver,Electronics,Tablets,Apple,90033.17,65.49,...,True,Valentine Sale,NaN,Delivered,2,2023,1,0.40,True,4.5
127128,TXN_2023_00082508_DUP,2023-09-29,CUST_2022_00015469,PROD_000278,Xiaomi Redmi 4A 16GB White,Electronics,Smartphones,Xiaomi,22108.7,31.35,...,TRUE,Amazon Great Indian Festival,5/5,Delivered,9,2023,3,0.21,True,4.1
127129,TXN_2023_00023903_DUP,2023-03-08,CUST_2019_00016252,PROD_001014,OnePlus OnePlus 10T 64GB White,Electronics,Smartphones,OnePlus,58697.1,23.90,...,True,Holi Festival,5.0,Delivered,3,2023,1,0.19,1,4.5
127130,TXN_2023_00093042_DUP,2023-10-04,CUST_2022_00015673,PROD_000195,Motorola Moto G4 32GB Blue,Electronics,Smartphones,Motorola,15514.86,33.62,...,True,Amazon Great Indian Festival,3.0,Delivered,10,2023,4,0.15,1,4.2
127131,TXN_2023_00042125_DUP,2023-05-02,CUST_2023_00040398,PROD_000876,Xiaomi Redmi Note 10 64GB White,Electronics,Smartphones,Xiaomi,29037.69,18.40,...,True,Summer Sale,NaN,Delivered,5,2023,2,0.19,False,4.0

In [6]:
year_2023.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges          10162
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        15259
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             88239
customer_rating           38484
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [7]:
year_2023['delivery_charges'] = year_2023['delivery_charges'].fillna(0.0)

In [8]:
year_2023.duplicated().sum()

np.int64(0)

In [9]:
year_2023['order_date'].isna().sum()

np.int64(0)

In [10]:
#Q1 datetime format 

year_2023['order_date'] = pd.to_datetime(
    year_2023['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2023['order_date'].dropna().median()

year_2023['order_date'] = (
    year_2023['order_date']
    .fillna(median_date)
)

# Standardize format
year_2023['order_date'] = (
    year_2023['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [11]:
year_2023['order_date'].iloc[15:50]

15    2023-06-01
16    2023-01-13
17    2023-09-01
18    2023-11-01
19    2023-01-15
20    2023-02-01
21    2023-01-15
22    2023-01-15
23    2023-04-01
24    2023-01-14
25    2023-10-01
26    2023-09-01
27    2023-01-17
28    2023-11-01
29    2023-03-01
30    2023-01-19
31    2023-04-01
32    2023-01-06
33    2023-03-01
34    2023-01-31
35    2023-01-21
36    2023-05-01
37    2023-01-31
38    2023-01-15
39    2023-08-01
40    2023-01-15
41    2023-09-01
42    2023-01-21
43    2023-10-01
44    2023-01-24
45    2023-01-17
46    2023-02-01
47    2023-01-30
48    2023-01-16
49    2023-01-21
Name: order_date, dtype: str

In [12]:
year_2023['original_price_inr'].iloc[16:45]

16     25915.37
17     17196.84
18     78154.48
19    123293.45
20     34831.05
21     77327.51
22    113407.25
23     20232.07
24    194115.74
25     24548.75
26    243080.32
27     279514.9
28     90040.94
29     25829.48
30      28715.3
31     53975.14
32     50049.74
33    Rs 19,076
34      35945.3
35     35045.86
36     98759.83
37     35945.58
38     115935.4
39      81602.7
40      51525.1
41     52758.95
42     20198.06
43      28832.1
44     15079.04
Name: original_price_inr, dtype: str

In [13]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2023['original_price_inr'] = year_2023['original_price_inr'].str.replace('₹', '', regex=False)
year_2023['original_price_inr'] = year_2023['original_price_inr'].str.replace('Rs', '', regex=False)
year_2023['original_price_inr'] = year_2023['original_price_inr'].str.replace(',', '', regex=False)
year_2023['original_price_inr'] = year_2023['original_price_inr'].astype(float)

year_2023['original_price_inr'].iloc[16:45]

16     25915.37
17     17196.84
18     78154.48
19    123293.45
20     34831.05
21     77327.51
22    113407.25
23     20232.07
24    194115.74
25     24548.75
26    243080.32
27    279514.90
28     90040.94
29     25829.48
30     28715.30
31     53975.14
32     50049.74
33     19076.00
34     35945.30
35     35045.86
36     98759.83
37     35945.58
38    115935.40
39     81602.70
40     51525.10
41     52758.95
42     20198.06
43     28832.10
44     15079.04
Name: original_price_inr, dtype: float64

In [14]:
year_2023['original_price_inr']

0          59416.51
1          19474.76
2          27097.23
3          12883.85
4         165637.56
            ...
127127     90033.17
127128     22108.70
127129     58697.10
127130     15514.86
127131     29037.69
Name: original_price_inr, Length: 127132, dtype: float64

In [15]:
year_2023['customer_rating'].value_counts()

customer_rating
4.5          27693
5.0          20926
4.0          19710
3.5           8585
3.0           4637
4/5           1190
4.5 stars      980
5.0 stars      720
4.0 stars      717
5/5            545
4.5/5.0        465
4              403
5.0/5.0        375
3/5            361
3.5 stars      329
4.0/5.0        316
3.0 stars      187
5              181
3.5/5.0        130
3              122
3.0/5.0         76
Name: count, dtype: int64

In [16]:
#Q3 - column to contain only numeric values representing the rating.
year_2023['customer_rating'] = year_2023['customer_rating'].astype(str) # Convert to string for processing
year_2023['customer_rating'] = year_2023['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2023['customer_rating'] = year_2023['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2023['customer_rating'] = year_2023['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2023['customer_rating'] = pd.to_numeric(year_2023['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [17]:
year_2023['customer_rating'].value_counts()

customer_rating
4.5    29138
5.0    22747
4.0    22336
3.5     9044
3.0     5383
Name: count, dtype: int64

In [18]:
year_2023['customer_city'].unique()

<StringArray>
[       'Kanpur',          'Pune',       'Lucknow',       'Chennai',
        'Mumbai',         'Surat', 'Visakhapatnam',    'Chandigarh',
     'Bangalore',     'Hyderabad',        'Indore',    'Saharanpur',
     'Moradabad',     'Gorakhpur',        'Nagpur',    'Coimbatore',
     'Ahmedabad',     'Allahabad',         'Delhi',         'Kochi',
         'Patna',       'Kolkata',        'Jaipur',      'Vadodara',
        'Meerut',      'Varanasi',   'Bhubaneswar',      'Bareilly',
     'BANGALORE',      'Ludhiana',       'Aligarh',      'Kolkata ',
      'Calcutta',       'Mumbai ',        'chenai',     'Delhi NCR',
         'DELHI',        'Madras',     'Bengaluru',         'delhi',
       'CHENNAI',       'kolkata',      'Chennai ',        'Bombay',
         'mumba',        'MUMBAI',     'Bengalore',     'New Delhi',
       'KOLKATA',      'Banglore']
Length: 50, dtype: str

In [39]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2023['customer_city'] = year_2023['customer_city'].replace(city_map)

year_2023['customer_city'] = year_2023['customer_city'].str.title()
year_2023['customer_city'].unique()

<StringArray>
[       'Kanpur',          'Pune',       'Lucknow',       'Chennai',
        'Mumbai',         'Surat', 'Visakhapatnam',    'Chandigarh',
     'Bengaluru',     'Hyderabad',        'Indore',    'Saharanpur',
     'Moradabad',     'Gorakhpur',        'Nagpur',    'Coimbatore',
     'Ahmedabad',     'Allahabad',         'Delhi',         'Kochi',
         'Patna',       'Kolkata',        'Jaipur',      'Vadodara',
        'Meerut',      'Varanasi',   'Bhubaneswar',      'Bareilly',
      'Ludhiana',       'Aligarh']
Length: 30, dtype: str

In [20]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2023[col] = year_2023[col].map(bool_map)

In [21]:
year_2023[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0             True               True             False
1            False               True             False
2             True               True             False
3            False               True             False
4             True              False             False

In [22]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2023['category'] = (
    year_2023['category']
    .replace(category_map)
)

In [23]:
year_2023['category'].value_counts()

category
Electronics    127132
Name: count, dtype: int64

In [24]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2023['delivery_days'] = year_2023['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2023['delivery_days'] = pd.to_numeric(
    year_2023['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2023.loc[
    (year_2023['delivery_days'] >= 0) &
    (year_2023['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2023.loc[
    (year_2023['delivery_days'] < 0) |
    (year_2023['delivery_days'] > 30) |
    (year_2023['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2023['delivery_days'] = year_2023['delivery_days'].astype(int)

In [25]:
year_2023['delivery_days'].value_counts()

delivery_days
1     35239
3     30942
2     21533
4     16522
5     10761
6      8311
7      2799
0       756
15      269
Name: count, dtype: int64

In [26]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2023.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2023 = year_2023.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2023.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 632
Duplicates after removal: 0

In [27]:
year_2023['original_price_inr'].describe()

count    1.265000e+05
mean     7.290249e+04
std      3.657453e+05
min     -2.531460e+05
25%      2.604860e+04
50%      3.923070e+04
75%      8.056033e+04
max      3.018865e+07
Name: original_price_inr, dtype: float64

In [28]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [29]:
#Q9 - column to contain the base price of the product in 2023.
year_2023 = year_2023.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2023['price_ratio'] = year_2023['original_price_inr'] / year_2023['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2023['price_ratio'] < 0.3) | (year_2023['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2023.loc[mask, 'original_price_inr'] = year_2023['base_price_2015'] # Replace outliers with base price
year_2023.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [30]:
year_2023['original_price_inr'].describe()

count    126500.000000
mean      58670.289521
std       46764.131966
min        1076.520000
25%       26131.780000
50%       39101.770000
75%       80248.630000
max      318161.030000
Name: original_price_inr, dtype: float64

In [31]:
year_2023['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [32]:
year_2023.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        15180
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             87794
customer_rating           38291
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [33]:
year_2023['customer_rating'].unique()

array([4. , 5. , 3.5, 3. , nan, 4.5])

In [34]:
year_2023['customer_rating'] = (year_2023['customer_rating'].replace(1, np.nan))

In [35]:
year_2023['festival_name'] = (year_2023['festival_name'].fillna('Regular Sale'))

In [41]:
year_2023['customer_age_group'] = year_2023['customer_age_group'].fillna('Unknown')
year_2023 = year_2023.dropna(subset=['customer_rating'])

In [42]:
year_2023.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [43]:
year_2023.to_csv(
    '2023_cleaned.csv',
    index=False
)

In [38]:
year_2023.iloc[16:30]

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
16,TXN_2023_00000017,2023-01-13,CUST_2018_00031443,PROD_000327,Oppo A71 64GB Blue,Electronics,Smartphones,Oppo,25915.37,0.00,...,False,Regular Sale,4.0,Delivered,1,2023,1,0.24,True,3.5
17,TXN_2023_00000018,2023-09-01,CUST_2023_00044711,PROD_001075,iQOO iQOO Z6 128GB Blue,Electronics,Smartphones,iQOO,17196.84,0.00,...,False,Regular Sale,4.0,Delivered,1,2023,1,0.23,True,4.6
18,TXN_2023_00000019,2023-11-01,CUST_2023_00033097,PROD_000697,OnePlus OnePlus 8 64GB Black,Electronics,Smartphones,OnePlus,78154.48,0.00,...,False,Regular Sale,5.0,Delivered,1,2023,1,0.25,True,4.1
19,TXN_2023_00000020,2023-01-15,CUST_2021_00029361,PROD_001117,Samsung Galaxy S23 Ultra 128GB White,Electronics,Smartphones,Samsung,123293.45,12.60,...,False,Regular Sale,4.0,Delivered,1,2023,1,0.20,False,4.5
20,TXN_2023_00000021,2023-02-01,CUST_2022_00017637,PROD_000289,Vivo V7 16GB Black,Electronics,Smartphones,Vivo,34831.05,0.00,...,False,Regular Sale,4.5,Delivered,1,2023,1,0.25,True,3.5
21,TXN_2023_00000022,2023-01-15,CUST_2023_00011966,PROD_000855,OnePlus OnePlus 9 Pro 128GB White,Electronics,Smartphones,OnePlus,77327.51,0.00,...,False,Regular Sale,5.0,Delivered,1,2023,1,0.24,True,3.7
22,TXN_2023_00000023,2023-01-15,CUST_2022_00044039,PROD_000003,Apple iPhone 6 64GB Black,Electronics,Smartphones,Apple,113407.25,0.00,...,False,Regular Sale,4.5,Delivered,1,2023,1,0.22,True,4.6
23,TXN_2023_00000024,2023-04-01,CUST_2019_00034610,PROD_000090,Motorola Moto G (3rd Gen) 32GB Blue,Electronics,Smartphones,Motorola,20232.07,0.00,...,False,Regular Sale,4.5,Delivered,1,2023,1,0.20,True,3.8
24,TXN_2023_00000025,2023-01-14,CUST_2020_00033849,PROD_000489,Apple iPhone 11 Pro 128GB Black,Electronics,Smartphones,Apple,194115.74,0.00,...,False,Regular Sale,4.5,Delivered,1,2023,1,0.17,True,4.0
25,TXN_2023_00000026,2023-10-01,CUST_2023_00030050,PROD_000406,Xiaomi Redmi 5A 128GB Black,Electronics,Smartphones,Xiaomi,24548.75,16.04,...,False,Regular Sale,3.0,Delivered,1,2023,1,0.17,True,3.2
26,TXN_2023_00000027,2023-09-01,CUST_2021_00042774,PROD_001625,Apple Ultrabook 8GB RAM Black,Electronics,Laptops,Apple,243080.32,0.00,...,False,Regular Sale,4.0,Delivered,1,2023,1,1.85,True,3.3
27,TXN_2023_00000028,2023-01-17,CUST_2022_00046029,PROD_000950,Apple iPhone 14 256GB White,Electronics,Smartphones,Apple,279514.90,20.55,...,False,Regular Sale,NaN,Delivered,1,2023,1,0.23,True,3.9
28,TXN_2023_00000029,2023-11-01,CUST_2023_00033692,PROD_001696,Samsung Mi Pad 4GB RAM Silver,Electronics,Tablets,Samsung,90040.94,0.00,...,False,Regular Sale,5.0,Delivered,1,2023,1,0.44,True,3.2
29,TXN_2023_00000030,2023-03-01,CUST_2021_00014837,PROD_000634,Oppo Reno 128GB White,Electronics,Smartphones,Oppo,25829.48,0.00,...,False,Regular Sale,3.5,Delivered,1,2023,1,0.25,True,3.6