In [3]:
import pandas as pd
import numpy as np

In [4]:
year_2024 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2024.csv")
year_2024

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2024_00000001,2024-01-03,CUST_2024_00003447,PROD_000387,OnePlus OnePlus 6 64GB White,Electronics,Smartphones,OnePlus,39348.44,0.00,...,False,NaN,NaN,Delivered,1,2024,1,0.24,True,3.4
1,TXN_2024_00000002,2024-01-09,CUST_2018_00008611,PROD_001357,Nothing Phone (2a) Plus 64GB Blue,Electronics,Smartphones,Nothing,"18,694.97",0.00,...,False,NaN,5.0,Delivered,1,2024,1,0.15,True,4.1
2,TXN_2024_00000003,2024-01-09,CUST_2024_00002076,PROD_001899,Xiaomi Watch Premium,Electronics,Smart Watch,Xiaomi,59276.71,17.19,...,False,NaN,NaN,Delivered,1,2024,1,0.06,TRUE,4.2
3,TXN_2024_00000004,2024-01-09,CUST_2024_00014530,PROD_000071,Xiaomi Redmi 2 32GB Black,Electronics,Smartphones,Xiaomi,32605.39,0.00,...,False,NaN,5.0,Delivered,1,2024,1,0.20,True,3.7
4,TXN_2024_00000005,22-01-2024,CUST_2022_00043625,PROD_001144,OnePlus OnePlus 11R 256GB White,Electronics,Smartphones,OnePlus,72805.3,18.89,...,True,Republic Day Sale,4.5,Delivered,1,2024,1,0.21,True,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121600,TXN_2024_00021368_DUP,31-03-2024,CUST_2024_00010041,PROD_000048,Samsung Galaxy J7 16GB White,Electronics,Smartphones,Samsung,27999.88,14.10,...,False,NaN,4.5,Delivered,3,2024,1,0.19,False,4.6
121601,TXN_2024_00030811_DUP,2024-04-13,CUST_2024_00038545,PROD_000623,Oppo F11 64GB White,Electronics,Smartphones,Oppo,29256.3,0.00,...,False,NaN,4.0,Returned,4,2024,2,0.22,True,4.6
121602,TXN_2024_00005850_DUP,2024-01-29,CUST_2016_00017631,PROD_001948,Noise Watch,Electronics,Smart Watch,Noise,33878.2,0.00,...,False,NaN,5.0,Delivered,1,2024,1,0.06,True,3.3
121603,TXN_2024_00005559_DUP,2024-01-29,CUST_2024_00023947,PROD_001900,Xiaomi Watch Deluxe,Electronics,Smart Watch,Xiaomi,38806.15,27.19,...,False,NaN,3.0,Delivered,1,2024,1,0.08,True,3.5
121604,TXN_2024_00032852_DUP,2024-04-14,CUST_2024_00027879,PROD_001717,Lenovo Slate 8GB RAM Black,Electronics,Tablets,Lenovo,104831.68,0.00,...,False,NaN,4.0,Delivered,4,2024,2,0.48,True,4.7

In [5]:
year_2024.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           9728
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        14601
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             84110
customer_rating           36680
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [6]:
year_2024['delivery_charges'] = year_2024['delivery_charges'].fillna(0.0)

In [7]:
year_2024.duplicated().sum()

np.int64(0)

In [8]:
year_2024['order_date'].isna().sum()

np.int64(0)

In [9]:
#Q1 datetime format 

year_2024['order_date'] = pd.to_datetime(
    year_2024['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2024['order_date'].dropna().median()

year_2024['order_date'] = (
    year_2024['order_date']
    .fillna(median_date)
)

# Standardize format
year_2024['order_date'] = (
    year_2024['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [10]:
year_2024['order_date'].iloc[15:50]

15    2024-01-28
16    2024-01-26
17    2024-01-14
18    2024-01-23
19    2024-01-18
20    2024-01-26
21    2024-01-21
22    2024-01-19
23    2024-01-27
24    2024-12-01
25    2024-01-20
26    2024-01-17
27    2024-07-01
28    2024-01-20
29    2024-01-24
30    2024-01-20
31    2024-01-30
32    2024-01-26
33    2024-01-28
34    2024-08-01
35    2024-01-17
36    2024-08-01
37    2024-01-19
38    2024-01-13
39    2024-01-20
40    2024-11-01
41    2024-02-01
42    2024-05-01
43    2024-01-26
44    2024-01-16
45    2024-11-01
46    2024-01-14
47    2024-07-01
48    2024-01-19
49    2024-01-21
Name: order_date, dtype: str

In [11]:
year_2024['original_price_inr'].iloc[16:45]

16      21555.05
17       47090.5
18      42799.62
19      25329.39
20      12034.77
21     102088.55
22      19477.53
23      29166.86
24      71213.13
25      20213.78
26      89605.67
27      27382.53
28      615353.3
29      60989.84
30      78952.86
31       29256.3
32     113349.23
33      17396.81
34       9176.76
35      29166.86
36      16276.97
37     112581.31
38      49461.27
39      40747.51
40      25378.99
41      25476.45
42    ₹92,502.60
43     132192.05
44     121639.68
Name: original_price_inr, dtype: str

In [12]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2024['original_price_inr'] = year_2024['original_price_inr'].str.replace('₹', '', regex=False)
year_2024['original_price_inr'] = year_2024['original_price_inr'].str.replace('Rs', '', regex=False)
year_2024['original_price_inr'] = year_2024['original_price_inr'].str.replace(',', '', regex=False)
year_2024['original_price_inr'] = year_2024['original_price_inr'].astype(float)

year_2024['original_price_inr'].iloc[16:45]

16     21555.05
17     47090.50
18     42799.62
19     25329.39
20     12034.77
21    102088.55
22     19477.53
23     29166.86
24     71213.13
25     20213.78
26     89605.67
27     27382.53
28    615353.30
29     60989.84
30     78952.86
31     29256.30
32    113349.23
33     17396.81
34      9176.76
35     29166.86
36     16276.97
37    112581.31
38     49461.27
39     40747.51
40     25378.99
41     25476.45
42     92502.60
43    132192.05
44    121639.68
Name: original_price_inr, dtype: float64

In [13]:
year_2024['original_price_inr']

0          39348.44
1          18694.97
2          59276.71
3          32605.39
4          72805.30
            ...
121600     27999.88
121601     29256.30
121602     33878.20
121603     38806.15
121604    104831.68
Name: original_price_inr, Length: 121605, dtype: float64

In [14]:
year_2024['customer_rating'].value_counts()

customer_rating
4.5          26482
5.0          19869
4.0          18906
3.5           8393
3.0           4483
4/5           1128
4.5 stars      983
5.0 stars      656
4.0 stars      653
5/5            505
4.5/5.0        455
5.0/5.0        380
4              379
3/5            338
4.0/5.0        327
3.5 stars      298
5              173
3.5/5.0        162
3.0 stars      159
3              104
3.0/5.0         92
Name: count, dtype: int64

In [15]:
#Q3 - column to contain only numeric values representing the rating.
year_2024['customer_rating'] = year_2024['customer_rating'].astype(str) # Convert to string for processing
year_2024['customer_rating'] = year_2024['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2024['customer_rating'] = year_2024['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2024['customer_rating'] = year_2024['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2024['customer_rating'] = pd.to_numeric(year_2024['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [16]:
year_2024['customer_rating'].value_counts()

customer_rating
4.5    27920
5.0    21583
4.0    21393
3.5     8853
3.0     5176
Name: count, dtype: int64

In [17]:
year_2024['customer_city'].unique()

<StringArray>
[      'Chennai',        'Mumbai',         'Surat',     'Ahmedabad',
         'Delhi',   'Bhubaneswar',     'Moradabad',        'Indore',
    'Chandigarh',          'Pune',        'Jaipur',       'Aligarh',
      'Varanasi',      'Vadodara',     'Hyderabad',        'Nagpur',
    'Coimbatore',     'Bangalore', 'Visakhapatnam',         'Kochi',
     'Allahabad',        'Meerut',       'Kolkata',       'Lucknow',
    'Saharanpur',      'Bareilly',     'Gorakhpur',      'Ludhiana',
         'Patna',        'Kanpur',      'Kolkata ',       'CHENNAI',
     'New Delhi',     'Bengaluru',     'Bengalore',       'kolkata',
        'chenai',         'mumba',     'Delhi NCR',         'delhi',
         'DELHI',        'Bombay',       'KOLKATA',        'Madras',
       'Mumbai ',     'BANGALORE',      'Chennai ',      'Banglore',
      'Calcutta',        'MUMBAI']
Length: 50, dtype: str

In [38]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2024['customer_city'] = year_2024['customer_city'].replace(city_map)

year_2024['customer_city'] = year_2024['customer_city'].str.title()
year_2024['customer_city'].unique()

<StringArray>
[      'Chennai',        'Mumbai',         'Surat',     'Ahmedabad',
         'Delhi',   'Bhubaneswar',     'Moradabad',        'Indore',
    'Chandigarh',          'Pune',        'Jaipur',       'Aligarh',
      'Varanasi',      'Vadodara',     'Hyderabad',        'Nagpur',
    'Coimbatore',     'Bengaluru', 'Visakhapatnam',         'Kochi',
     'Allahabad',        'Meerut',       'Kolkata',       'Lucknow',
    'Saharanpur',      'Bareilly',     'Gorakhpur',      'Ludhiana',
         'Patna',        'Kanpur']
Length: 30, dtype: str

In [19]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2024[col] = year_2024[col].map(bool_map)

In [20]:
year_2024[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0             True               True             False
1             True               True             False
2             True               True             False
3            False               True             False
4             True               True              True

In [21]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2024['category'] = (
    year_2024['category']
    .replace(category_map)
)

In [22]:
year_2024['category'].value_counts()

category
Electronics    121605
Name: count, dtype: int64

In [23]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2024['delivery_days'] = year_2024['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2024['delivery_days'] = pd.to_numeric(
    year_2024['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2024.loc[
    (year_2024['delivery_days'] >= 0) &
    (year_2024['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2024.loc[
    (year_2024['delivery_days'] < 0) |
    (year_2024['delivery_days'] > 30) |
    (year_2024['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2024['delivery_days'] = year_2024['delivery_days'].astype(int)

In [24]:
year_2024['delivery_days'].value_counts()

delivery_days
1     36086
3     29325
2     22129
4     14199
5      9456
6      7097
7      2354
0       714
15      245
Name: count, dtype: int64

In [25]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2024.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2024 = year_2024.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2024.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 605
Duplicates after removal: 0

In [26]:
year_2024['original_price_inr'].describe()

count    1.210000e+05
mean     6.792007e+04
std      3.473098e+05
min     -2.569432e+05
25%      2.403066e+04
50%      3.638444e+04
75%      7.349270e+04
max      2.485294e+07
Name: original_price_inr, dtype: float64

In [27]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [28]:
#Q9 - column to contain the base price of the product in 2024.
year_2024 = year_2024.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2024['price_ratio'] = year_2024['original_price_inr'] / year_2024['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2024['price_ratio'] < 0.3) | (year_2024['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2024.loc[mask, 'original_price_inr'] = year_2024['base_price_2015'] # Replace outliers with base price
year_2024.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [29]:
year_2024['original_price_inr'].describe()

count    121000.000000
mean      54261.869350
std       44158.442787
min        1073.980000
25%       24056.880000
50%       36295.920000
75%       73188.390000
max      323504.370000
Name: original_price_inr, dtype: float64

In [30]:
year_2024['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [31]:
year_2024.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group        14520
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             83670
customer_rating           36488
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [32]:
year_2024['customer_rating'].unique()

array([nan, 5. , 4.5, 3.5, 4. , 3. ])

In [33]:
year_2024['customer_rating'] = (year_2024['customer_rating'].replace(1, np.nan))

In [34]:
year_2024['festival_name'] = (year_2024['festival_name'].fillna('Regular Sale'))

In [40]:
year_2024['customer_age_group'] = year_2024['customer_age_group'].fillna('Unknown')
year_2024 = year_2024.dropna(subset=['customer_rating'])

In [41]:
year_2024.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [44]:
year_2024.to_csv(
    '2024_cleaned.csv',
    index=False
)

In [43]:
year_2024

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
1,TXN_2024_00000002,2024-09-01,CUST_2018_00008611,PROD_001357,Nothing Phone (2a) Plus 64GB Blue,Electronics,Smartphones,Nothing,18694.97,0.00,...,False,Regular Sale,5.0,Delivered,1,2024,1,0.15,True,4.1
3,TXN_2024_00000004,2024-09-01,CUST_2024_00014530,PROD_000071,Xiaomi Redmi 2 32GB Black,Electronics,Smartphones,Xiaomi,32605.39,0.00,...,False,Regular Sale,5.0,Delivered,1,2024,1,0.20,True,3.7
4,TXN_2024_00000005,2024-01-22,CUST_2022_00043625,PROD_001144,OnePlus OnePlus 11R 256GB White,Electronics,Smartphones,OnePlus,72805.30,18.89,...,True,Republic Day Sale,4.5,Delivered,1,2024,1,0.21,True,3.6
5,TXN_2024_00000006,2024-01-25,CUST_2019_00006801,PROD_000858,OnePlus OnePlus Nord 2 128GB Black,Electronics,Smartphones,OnePlus,58371.09,22.60,...,True,Republic Day Sale,4.5,Delivered,1,2024,1,0.22,True,3.7
6,TXN_2024_00000007,2024-12-01,CUST_2019_00039334,PROD_000568,Xiaomi Mi A3 256GB White,Electronics,Smartphones,Xiaomi,13588.99,9.35,...,False,Regular Sale,3.5,Delivered,1,2024,1,0.16,True,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120994,TXN_2024_00120995,2024-04-12,CUST_2024_00009750,PROD_000747,Realme Realme X50 Pro 128GB White,Electronics,Smartphones,Realme,21385.86,0.00,...,False,Regular Sale,5.0,Cancelled,12,2024,4,0.17,True,3.3
120995,TXN_2024_00120996,2024-11-12,CUST_2024_00003671,PROD_000161,OnePlus OnePlus 3 16GB Blue,Electronics,Smartphones,OnePlus,64261.89,0.00,...,False,Regular Sale,4.0,Cancelled,12,2024,4,0.20,True,4.3
120996,TXN_2024_00120997,2024-12-21,CUST_2024_00026645,PROD_000783,Oppo A52 128GB Black,Electronics,Smartphones,Oppo,20085.76,0.00,...,False,Regular Sale,3.5,Delivered,12,2024,4,0.25,True,4.4
120997,TXN_2024_00120998,2024-12-23,CUST_2024_00007114,PROD_001088,Apple iPhone 15 Pro 128GB White,Electronics,Smartphones,Apple,264588.38,0.00,...,False,Regular Sale,5.0,Cancelled,12,2024,4,0.20,True,4.0
120998,TXN_2024_00120999,2024-06-12,CUST_2024_00006010,PROD_001161,Xiaomi Poco F5 64GB Black,Electronics,Smartphones,Xiaomi,26051.45,0.00,...,False,Regular Sale,4.5,Delivered,12,2024,4,0.20,True,4.2