In [1]:
import pandas as pd
import numpy as np

In [2]:
year_2025 = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_2025.csv")
year_2025

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2025_00000001,2025-01-08,CUST_2025_00005600,PROD_000627,Oppo F11 Pro 128GB Black,Electronics,Smartphones,Oppo,10234.12,0.00,...,False,NaN,4.5,Delivered,1,2025,1,0.15,True,4.4
1,TXN_2025_00000002,01/15/2025,CUST_2022_00027099,PROD_001699,Samsung Slate 4GB RAM Silver,Electronics,Tablets,Samsung,38241.08,0.00,...,False,NaN,NaN,Returned,1,2025,1,0.64,TRUE,3.4
2,TXN_2025_00000003,2025-01-26,CUST_2021_00027917,PROD_001242,Apple iPhone 16 Plus 64GB Black,Electronics,Smartphones,Apple,121974.26,32.04,...,True,Republic Day Sale,NaN,Returned,1,2025,1,0.18,True,3.4
3,TXN_2025_00000004,2025-01-04,CUST_2025_00004184,PROD_000979,Samsung Galaxy S22+ 128GB White,Electronics,Smartphones,Samsung,59075.7,0.00,...,False,NaN,3.5,Delivered,1,2025,1,0.24,False,3.3
4,TXN_2025_00000005,2025-01-03,CUST_2025_00005205,PROD_001876,Apple Watch Premium,Electronics,Smart Watch,Apple,74269.31,0.00,...,False,NaN,5.0/5.0,Returned,1,2025,1,0.05,TRUE,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77380,TXN_2025_00019019_DUP,2025-04-07,CUST_2022_00004500,PROD_000136,Samsung Galaxy S7 Edge 16GB Blue,Electronics,Smartphones,Samsung,67658.04,0.00,...,False,NaN,3.5,Delivered,4,2025,2,0.16,True,3.4
77381,TXN_2025_00053859_DUP,09-10-2025,CUST_2025_00013666,PROD_000527,Samsung Galaxy A50 64GB White,Electronics,Smartphones,Samsung,19905.88,24.29,...,False,NaN,3.5 stars,Delivered,10,2025,4,0.20,False,4.2
77382,TXN_2025_00030006_DUP,2025-06-29,CUST_2025_00011941,PROD_000839,Samsung Galaxy Note 21 256GB White,Electronics,Smartphones,Samsung,75655.18,30.26,...,True,Back to School,4.0,Delivered,6,2025,2,0.22,True,4.1
77383,TXN_2025_00066716_DUP,2025-11-21,CUST_2025_00000199,PROD_001581,ASUS Gaming 4GB RAM Black,Electronics,Laptops,ASUS,125461.24,0.00,...,False,NaN,4.5,Delivered,11,2025,4,2.57,False,3.0
77384,TXN_2025_00039367_DUP,2025-07-26,CUST_2025_00019685,PROD_001191,Realme Realme C55 128GB Blue,Electronics,Smartphones,Realme,15852.16,0.00,...,False,NaN,4.0,Delivered,7,2025,3,0.24,True,3.7

In [3]:
year_2025.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges           6196
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         9296
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             53750
customer_rating           23464
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [4]:
year_2025['delivery_charges'] = year_2025['delivery_charges'].fillna(0.0)

In [5]:
year_2025.duplicated().sum()

np.int64(0)

In [6]:
year_2025['order_date'].isna().sum()

np.int64(0)

In [7]:
#Q1 datetime format 

year_2025['order_date'] = pd.to_datetime(
    year_2025['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

# Fill invalid dates
median_date = year_2025['order_date'].dropna().median()

year_2025['order_date'] = (
    year_2025['order_date']
    .fillna(median_date)
)

# Standardize format
year_2025['order_date'] = (
    year_2025['order_date']
    .dt.strftime('%Y-%m-%d')
)

In [8]:
year_2025['order_date'].iloc[15:50]

15    2025-01-25
16    2025-01-20
17    2025-01-26
18    2025-01-27
19    2025-01-31
20    2025-01-04
21    2025-10-01
22    2025-01-18
23    2025-01-15
24    2025-01-28
25    2025-01-01
26    2025-01-16
27    2025-01-24
28    2025-01-26
29    2025-01-13
30    2025-03-01
31    2025-01-27
32    2025-01-01
33    2025-05-01
34    2025-01-25
35    2025-01-01
36    2025-01-15
37    2025-01-21
38    2025-01-23
39    2025-06-01
40    2025-07-01
41    2025-01-24
42    2025-01-29
43    2025-01-16
44    2025-01-25
45    2025-01-16
46    2025-01-25
47    2025-08-01
48    2025-01-23
49    2025-01-26
Name: order_date, dtype: str

In [9]:
year_2025['original_price_inr'].iloc[16:45]

16     Rs 21,896
17      24121.43
18      10167.72
19      21769.59
20       6857.33
21     164649.47
22      15637.87
23      70820.24
24      63889.14
25     159640.59
26      42943.84
27      59389.39
28       7751.41
29      64369.46
30    ₹56,481.16
31      20581.09
32      27725.18
33      38941.95
34      15092.97
35      25067.73
36      15496.94
37       27850.0
38      44122.16
39      29839.75
40      82221.05
41        6182.9
42    Rs 187,569
43      30349.07
44      28105.68
Name: original_price_inr, dtype: str

In [10]:
#Q2 -  column to contain only numeric values in Indian Rupees.

year_2025['original_price_inr'] = year_2025['original_price_inr'].str.replace('₹', '', regex=False)
year_2025['original_price_inr'] = year_2025['original_price_inr'].str.replace('Rs', '', regex=False)
year_2025['original_price_inr'] = year_2025['original_price_inr'].str.replace(',', '', regex=False)
year_2025['original_price_inr'] = year_2025['original_price_inr'].astype(float)

year_2025['original_price_inr'].iloc[16:45]

16     21896.00
17     24121.43
18     10167.72
19     21769.59
20      6857.33
21    164649.47
22     15637.87
23     70820.24
24     63889.14
25    159640.59
26     42943.84
27     59389.39
28      7751.41
29     64369.46
30     56481.16
31     20581.09
32     27725.18
33     38941.95
34     15092.97
35     25067.73
36     15496.94
37     27850.00
38     44122.16
39     29839.75
40     82221.05
41      6182.90
42    187569.00
43     30349.07
44     28105.68
Name: original_price_inr, dtype: float64

In [11]:
year_2025['original_price_inr']

0         10234.12
1         38241.08
2        121974.26
3         59075.70
4         74269.31
           ...
77380     67658.04
77381     19905.88
77382     75655.18
77383    125461.24
77384     15852.16
Name: original_price_inr, Length: 77385, dtype: float64

In [12]:
year_2025['customer_rating'].value_counts()

customer_rating
4.5          16833
5.0          12533
4.0          12246
3.5           5221
3.0           2773
4/5            748
4.5 stars      579
4.0 stars      430
5.0 stars      391
4.5/5.0        320
5/5            304
4              269
5.0/5.0        245
4.0/5.0        205
3/5            192
3.5 stars      191
3.0 stars      115
5              108
3.5/5.0         86
3               74
3.0/5.0         58
Name: count, dtype: int64

In [13]:
#Q3 - column to contain only numeric values representing the rating.
year_2025['customer_rating'] = year_2025['customer_rating'].astype(str) # Convert to string for processing
year_2025['customer_rating'] = year_2025['customer_rating'].str.split('/').str[0] # Keep only the part before the slash
year_2025['customer_rating'] = year_2025['customer_rating'].str.replace('stars', '', regex=False) # Remove 'stars' and empty strings if present
year_2025['customer_rating'] = year_2025['customer_rating'].str.strip() # Remove any leading/trailing whitespace
year_2025['customer_rating'] = pd.to_numeric(year_2025['customer_rating'], errors='coerce') # Convert to numeric, coercing errors to NaN

In [14]:
year_2025['customer_rating'].value_counts()

customer_rating
4.5    17732
4.0    13898
5.0    13581
3.5     5498
3.0     3212
Name: count, dtype: int64

In [15]:
year_2025['customer_city'].unique()

<StringArray>
[        'Delhi',     'Hyderabad',     'Bangalore',    'Chandigarh',
       'Kolkata',          'Pune',     'Ahmedabad',   'Bhubaneswar',
       'Chennai',         'Surat',      'Vadodara',        'Nagpur',
      'Ludhiana', 'Visakhapatnam',        'Indore',        'Jaipur',
        'Kanpur',      'Bareilly',       'Aligarh',        'Mumbai',
    'Coimbatore',         'Patna',     'Moradabad',     'BANGALORE',
     'Gorakhpur',       'Lucknow',    'Saharanpur',         'Kochi',
     'Allahabad',      'Varanasi',        'Meerut',         'DELHI',
      'Banglore',        'Madras',      'Calcutta',      'Chennai ',
        'chenai',         'mumba',       'kolkata',     'New Delhi',
     'Delhi NCR',       'Mumbai ',       'CHENNAI',        'Bombay',
        'MUMBAI',         'delhi',     'Bengaluru',       'KOLKATA',
     'Bengalore',      'Kolkata ']
Length: 50, dtype: str

In [38]:
#Q4 - column to contain standardized city names.
city_map = {
    # Mumbai
    'Bombay': 'Mumbai',
    'mumba': 'Mumbai',
    'Mumbai ': 'Mumbai',
    
    # Bengaluru
    'Bengalore': 'Bengaluru',
    'Bengaluru': 'Bengaluru',
    'Banglore': 'Bengaluru',
    'Bangalore': 'Bengaluru',
    'Bangalore ': 'Bengaluru',
    
    # Chennai
    'Madras': 'Chennai',
    'Chennai': 'Chennai',
    'Chennai ': 'Chennai',
    'Chenai': 'Chennai',
    'Chenai ': 'Chennai',
    
    # Kolkata
    'Calcutta': 'Kolkata',
    'Kolkata ': 'Kolkata',
    
    # Delhi
    'New Delhi': 'Delhi',
    'Delhi NCR': 'Delhi'
}


year_2025['customer_city'] = year_2025['customer_city'].replace(city_map)

year_2025['customer_city'] = year_2025['customer_city'].str.title()
year_2025['customer_city'].unique()

<StringArray>
[        'Delhi',    'Chandigarh',       'Kolkata',       'Chennai',
      'Ludhiana',          'Pune', 'Visakhapatnam',     'Hyderabad',
        'Indore',        'Jaipur',        'Nagpur',         'Surat',
      'Bareilly',     'Ahmedabad',     'Bengaluru',       'Aligarh',
        'Kanpur',        'Mumbai',    'Coimbatore',         'Patna',
     'Moradabad',     'Gorakhpur',   'Bhubaneswar',    'Saharanpur',
         'Kochi',      'Vadodara',       'Lucknow',     'Allahabad',
        'Meerut',      'Varanasi']
Length: 30, dtype: str

In [39]:
year_2025['customer_state'].unique()

<StringArray>
[         'Delhi',         'Punjab',    'West Bengal',     'Tamil Nadu',
    'Maharashtra', 'Andhra Pradesh',      'Telangana', 'Madhya Pradesh',
      'Rajasthan',        'Gujarat',  'Uttar Pradesh',      'Karnataka',
          'Bihar',         'Odisha',         'Kerala']
Length: 15, dtype: str

In [17]:
#Q5 - columns to contain boolean values (True/False).

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

bool_map = {
    'True': True,
    'TRUE': True,
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    True: True,

    'False': False,
    'FALSE': False,
    'No': False,
    'N': False,
    '0': False,
    0: False,
    False: False
}

for col in bool_cols:
    year_2025[col] = year_2025[col].map(bool_map)

In [18]:
year_2025[bool_cols].head()

   is_prime_member  is_prime_eligible  is_festival_sale
0            False               True             False
1             True               True             False
2             True               True              True
3             True              False             False
4             True               True             False

In [19]:
#Q6 - column to contain standardized product categories.

category_map = {
    'ELECTRONICS': 'Electronics',
    'Electronic': 'Electronics',
    'Electronicss': 'Electronics',
    'Electronics & Accessories': 'Electronics'
}

year_2025['category'] = (
    year_2025['category']
    .replace(category_map)
)

In [20]:
year_2025['category'].value_counts()

category
Electronics    77385
Name: count, dtype: int64

In [21]:
#Q7 - column to contain numeric values representing delivery days.
# Replace text values with numeric equivalents
year_2025['delivery_days'] = year_2025['delivery_days'].replace({
    'Same Day': 0,
    'Express': 1,
    '1-2 days': 2
})

# Convert to numeric
year_2025['delivery_days'] = pd.to_numeric(
    year_2025['delivery_days'],
    errors='coerce'
)

# Calculate median from valid values
valid_median = year_2025.loc[
    (year_2025['delivery_days'] >= 0) &
    (year_2025['delivery_days'] <= 30),
    'delivery_days'
].median()

# Replace invalid values
year_2025.loc[
    (year_2025['delivery_days'] < 0) |
    (year_2025['delivery_days'] > 30) |
    (year_2025['delivery_days'].isna()),
    'delivery_days'
] = valid_median

# Convert to integer
year_2025['delivery_days'] = year_2025['delivery_days'].astype(int)

In [22]:
year_2025['delivery_days'].value_counts()

delivery_days
1     24538
3     17997
2     15369
4      8112
5      5427
6      4019
7      1308
0       465
15      150
Name: count, dtype: int64

In [23]:
# Q8: Duplicate Detection & Removal

# Define columns that represent a unique transaction item
dup_cols = ['customer_id', 'product_id', 'order_date','quantity' ,'final_amount_inr', 'payment_method']

# Check number of duplicates
duplicate_count = year_2025.duplicated(subset=dup_cols).sum()
print("Number of duplicate rows:", duplicate_count)

# Remove duplicates
year_2025 = year_2025.drop_duplicates(subset=dup_cols, keep='first')

# Verify
print("Duplicates after removal:", year_2025.duplicated(subset=dup_cols).sum())

Number of duplicate rows: 385
Duplicates after removal: 0

In [24]:
year_2025['original_price_inr'].describe()

count    7.700000e+04
mean     6.021560e+04
std      3.121658e+05
min     -2.392465e+05
25%      2.135147e+04
50%      3.183149e+04
75%      6.359767e+04
max      2.375135e+07
Name: original_price_inr, dtype: float64

In [25]:
catalog = pd.read_csv(r"C:\Users\Admin\Documents\amazon\CSV\amazon_india_products_catalog.csv")

catalog = catalog[['product_id', 'base_price_2015']]

In [26]:
#Q9 - column to contain the base price of the product in 2025.
year_2025 = year_2025.merge(catalog, on='product_id', how='left') # Merge to get base price
year_2025['price_ratio'] = year_2025['original_price_inr'] / year_2025['base_price_2015'] # Calculate price ratio to identify outliers
mask = (year_2025['price_ratio'] < 0.3) | (year_2025['price_ratio'] > 3) # Define outliers as those with price ratio less than 0.3 or greater than 3


year_2025.loc[mask, 'original_price_inr'] = year_2025['base_price_2015'] # Replace outliers with base price
year_2025.drop(columns=['base_price_2015', 'price_ratio'], inplace=True) # Clean up temporary columns

In [27]:
year_2025['original_price_inr'].describe()

count     77000.000000
mean      48203.907385
std       39738.784307
min        1067.270000
25%       21421.500000
50%       31835.380000
75%       62953.490000
max      314486.770000
Name: original_price_inr, dtype: float64

In [28]:
year_2025['festival_name'].unique()

<StringArray>
[                           nan,            'Republic Day Sale',
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [29]:
year_2025.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city                 0
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group         9240
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             53474
customer_rating           23338
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [30]:
year_2025['customer_rating'].unique()

array([4.5, nan, 3.5, 5. , 3. , 4. ])

In [31]:
year_2025['customer_rating'] = (year_2025['customer_rating'].replace(1, np.nan))

In [32]:
year_2025['festival_name'] = (year_2025['festival_name'].fillna('Regular Sale'))

In [33]:
year_2025['customer_age_group'] = year_2025['customer_age_group'].fillna('Unknown')
year_2025 = year_2025.dropna(subset=['customer_rating'])

In [34]:
year_2025.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

In [35]:
year_2025.to_csv(
    '2025_cleaned.csv',
    index=False
)

In [37]:
year_2025['payment_method'].unique()

<StringArray>
['UPI', 'Credit Card', 'COD', 'Debit Card', 'Net Banking', 'BNPL', 'Wallet']
Length: 7, dtype: str

In [36]:
year_2025

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2025_00000001,2025-08-01,CUST_2025_00005600,PROD_000627,Oppo F11 Pro 128GB Black,Electronics,Smartphones,Oppo,10234.12,0.00,...,False,Regular Sale,4.5,Delivered,1,2025,1,0.15,True,4.4
3,TXN_2025_00000004,2025-04-01,CUST_2025_00004184,PROD_000979,Samsung Galaxy S22+ 128GB White,Electronics,Smartphones,Samsung,59075.70,0.00,...,False,Regular Sale,3.5,Delivered,1,2025,1,0.24,False,3.3
4,TXN_2025_00000005,2025-03-01,CUST_2025_00005205,PROD_001876,Apple Watch Premium,Electronics,Smart Watch,Apple,74269.31,0.00,...,False,Regular Sale,5.0,Returned,1,2025,1,0.05,True,4.1
5,TXN_2025_00000006,2025-07-01,CUST_2024_00000334,PROD_001132,OnePlus OnePlus Nord 3 128GB Black,Electronics,Smartphones,OnePlus,42119.59,20.07,...,False,Regular Sale,5.0,Delivered,1,2025,1,0.17,True,3.8
10,TXN_2025_00000011,2025-10-01,CUST_2025_00019845,PROD_000782,Oppo A52 64GB Black,Electronics,Smartphones,Oppo,24841.29,25.74,...,False,Regular Sale,4.5,Delivered,1,2025,1,0.16,True,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76994,TXN_2025_00076995,2025-12-13,CUST_2022_00044727,PROD_000941,Oppo Reno 6 128GB Black,Electronics,Smartphones,Oppo,28360.06,10.83,...,False,Regular Sale,4.5,Delivered,12,2025,4,0.18,True,3.5
76995,TXN_2025_00076996,2025-01-12,CUST_2025_00020497,PROD_000262,OnePlus OnePlus 5 16GB Black,Electronics,Smartphones,OnePlus,27337.72,17.49,...,False,Regular Sale,4.0,Delivered,12,2025,4,0.20,True,4.6
76997,TXN_2025_00076998,2025-12-31,CUST_2021_00023963,PROD_001476,Realme Realme 13 128GB Blue,Electronics,Smartphones,Realme,26769.50,0.00,...,False,Regular Sale,5.0,Delivered,12,2025,4,0.21,True,3.5
76998,TXN_2025_00076999,2025-12-12,CUST_2025_00019394,PROD_001739,Realme iPad 4GB RAM Silver,Electronics,Tablets,Realme,133854.95,0.00,...,False,Regular Sale,5.0,Delivered,12,2025,4,0.51,True,4.5
76999,TXN_2025_00077000,2025-12-24,CUST_2021_00014781,PROD_000133,Samsung Galaxy S7 Edge 32GB Black,Electronics,Smartphones,Samsung,99038.79,0.00,...,False,Regular Sale,3.5,Delivered,12,2025,4,0.24,True,4.6